<?php /* @var Blugento_UploadFiles_Block_Adminhtml_System_Config_Form_Button $this*/ ?>

<table width="100%">
    <tr>
        <td class="value"><input type="file" name="files[]" id="file" multiple/></td>
    </tr>
    <tr>
        <td class="label"><label for="files"></label></td>
        <td class="value">
            <button title="<?php echo $this->__('Upload Selected Files'); ?>" type="button" class="scalable save" onclick="configForm.submit()" style="">
                <span><span><span><?php echo $this->__('Upload Selected Files'); ?></span></span></span>
            </button>
        </td>
        <td class="value">
            <button title="<?php echo $this->__('Unzip Archive'); ?>" type="button" class="scalable save" onclick="setLocation('<?php echo $this->getUnzipUrl() ?>')" style="">
                <span><span><span><?php echo $this->__('Unzip Archive'); ?></span></span></span>
            </button>
        </td>
    </tr>
</table>
