<?php
/**
 * @category    design
 * @package     rwd_default
 */
?>

<?php $_shipment = $this->getShipment() ?>
<?php $_order    = $this->getOrder() ?>

<?php if ($_shipment && $_order): ?>

    <?php $_items     = $_order->getAllItems() ?>
    <?php $_itemCount = count($_items) ?>
    <table class="items" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td class="items-box">
                <table cellpadding="0" cellspacing="0" border="0">
                    <thead>
                      <tr>
                        <th class="cell-name">
                            <?php if ($_itemCount > 1): ?>
                                <?php echo $this->__('Items in your order'); ?>
                            <?php else: ?>
                                <?php echo $this->__('Item in your order'); ?>
                            <?php endif; ?>
                        </th>
                        <th class="cell-name align-center">
                            <?php echo $this->__('Qty'); ?>
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php $i = 0; ?>
                      <?php foreach ($_shipment->getAllItems() as $_item): ?>
                          <?php if ($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
                          <?php echo $this->getItemHtml($_item) ?>
                      <?php endforeach; ?>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>
<?php endif; ?>
