<?php
/**
 * Blugento_Cart_Block_Form
 *
 * Copyright (C) 2015-2016 Blugento <contact@blugento.com>
 * LICENSE: GNU General Public License for more details <http://opensource.org/licenses/gpl-license.php>
 *
 * @package Blugento_Cart
 * @author Simona Trifan <simona.plesuvu@mindmagnetsoftware.com>
 * @link http://www.blugento.com
 */
$product = $this->getInquiryProduct();
$productID = $this->getInquiryProductID();
?>

<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" enctype="multipart/form-data">
    <input type="hidden" name="inquiry_product" id="inquiry_product" value="<?php echo $product; ?>" />
    <input type="hidden" name="inquiry_product_id" id="inquiry_product_id" value="<?php echo $productID; ?>" />
    <input type="hidden" name="redirect_to" value="poze-tip-polaroid">
    <div class="fieldset">

        <h2><?php echo $product; ?></h2>

        <h2 class="legend"><?php echo Mage::helper('blugento_cart')->__('Send your inquiry') ?></h2>
        <ul class="form-list form-list--inline">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><?php echo Mage::helper('blugento_cart')->__('Name') ?><em>*</em></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('blugento_cart')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><?php echo Mage::helper('blugento_cart')->__('Email address') ?><em>*</em></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('blugento_cart')->__('Email address')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('blugento_cart')->__('Phone number') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('blugento_cart')->__('Phone number')) ?>" value="" class="input-text" type="tel" />
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><?php echo Mage::helper('blugento_cart')->__('Your inquiry') ?><em>*</em></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('blugento_cart')->__('Your inquiry')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><?php echo Mage::helper('blugento_cart')->__('Your pictures') ?><em>*</em></label>
                <div class="input-box">
                <input type="file" class="upload_file_input" name="blugento_files[]" multiple="multiple" accept="image/*">
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('blugento_cart')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('blugento_cart')->__('Send Inquiry')) ?>" class="button"><span><span><?php echo Mage::helper('blugento_cart')->__('Send Inquiry') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
</script>
