<?php
    $_checkoutAgreementsPosition = (int) ($this->getLayout()->getBlock('root')->getCheckoutAgreementsPosition() ?: 1);
    $_checkoutViewPageOrientation = (int) ($this->getLayout()->getBlock('root')->getCheckoutViewPageOrientation() ?: 2);
?>

<?php if ($_checkoutAgreementsPosition == 2): ?>
    <?php echo $this->getChildHtml('agreements') ?>
<?php endif; ?>

<?php echo $this->getChildHtml('items_before') ?>

<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <tbody>
        <?php foreach ($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </tbody>
    </table>
    <table class="data-table" id="checkout-review-table-totals">
        <?php echo $this->getChildHtml('totals'); ?>
    </table>
</div>

<?php echo $this->getChildHtml('items_after'); ?>

<script>
//<![CDATA[
    truncateOptions();
//]]>
</script>

<div id="checkout-review-submit">
    <?php if ($_checkoutAgreementsPosition == 1): ?>
        <?php echo $this->getChildHtml('agreements') ?>
    <?php endif; ?>

    <div class="buttons-set" id="review-buttons-container">
        <?php if ($_checkoutViewPageOrientation != 2): ?>
            <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php endif; ?>

        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>

    <script>
    //<![CDATA[
	    review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', 'checkout-agreements');
    //]]>
    </script>
</div>
