<?php $_item = $this->getItem() ?>
<?php
if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/personalized')->isEnabled() && Mage::helper('personalized/data')->isItemPersonalized($_item)) {
	$options    = $this->getOptionList();
	$helper     = Mage::helper('personalized/data');
	$showCustom = true;

	if ($_item->getProductType() == 'configurable') {
		foreach ($_item->getOrder()->getAllItems() as $item) {
			if ($item->getParentItemId() == $_item->getId()) {
				$productOptions = $item->getProductOptions();
				$additionalOption = $productOptions['additional_options'];
				$options = array_merge($options, $additionalOption);
			}
		}
	}
	
	$imageNames  = $helper->getImageName($options);
	$imageName   = implode(",", $imageNames);
	$downloadUrl = Mage::getUrl('personalized/index/download/', array('names' => $imageName));
	$imageurl    = $helper->getImageUrl($options);
	$counter     = 1;
	
	if (!count($imageurl)) {
		$showCustom = false;
	}
}
?>
<tr>

    <?php if (Mage::getStoreConfig('blugento_checkout/general/product_image_enabled')): ?>
        <td>
	        <?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/personalized')->isEnabled() && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
		        <img src="<?php echo $imageurl[0]; ?>" width="160" height="160" class="img-responsive" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
	        <?php else : ?>
                <img src="<?php echo $this->getProductThumbnail()->resize(80,80); ?>" width="80" height="80" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
	        <?php endif; ?>
        </td>
    <?php endif; ?>

    <td>
        <span class="label"><span><?php echo $this->__('SKU') ?></span>: <?php echo $_item->getSku() ?></span>
        <h3 class="product-name"><?php echo $this->escapeHtml($this->getProductName()) ?></h3>
	    <?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
		    <?php if ($showCustom) : ?>
			    <a class="preview-link" style="float: none; margin: 0;" data-modal="open-<?php echo $_item->getId() ?>">
				    <?php echo $this->__('Preview Images'); ?>
			    </a>
			    <div class="modal-wrapper" data-modal="wrapper-<?php echo $_item->getId() ?>">
				    <div class="modal-content">
					    <a class="close-modal" data-modal="close-<?php echo $_item->getId() ?>">&times;</a>
					    <div class="text">
						    <div class="callbacks_container">
							    <ul class="rslides" id="productpersonalized-<?php echo $_item->getId() ?>">
								    <?php foreach ($imageurl as $image) :
									    if($counter % 2 != 0 && $image != 'blank') :
										    ?>
										    <li>
											    <img alt="personalized-preview-image" src=<?php echo $image ?> />
										    </li>
									    <?php endif;
									    $counter++;
								    endforeach; ?>
							    </ul>
						    </div>
					    </div>
				    </div>
			    </div>
		    <?php endif; ?>
		    <div class="personalized-download-link" style="display: block;">
			    <a href="<?php echo $downloadUrl; ?>"><?php echo $this->__('Download Images'); ?></a>
		    </div>
	    <?php endif; ?>
        <?php if ($_options = $this->getOptionList()) : ?>
	        <dl class="item-options">
		        <?php foreach ($_options as $_option) : ?>
			        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
			        <?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
				        <?php $text_object = 1; ?>
				        <?php if (isset($_option['code']) && ($_option['code'] == 'milople_imageurl' || $_option['code'] == 'milople_row_images' || $_option['code'] == 'text' . $text_object || $_option['code'] == 'text' . $text_object . '_font_family' || $_option['code'] == 'text' . $text_object . '_font_size')) :
					        if ($_option['code'] == 'text' . $text_object . '_font_size') :
						        $text_object++;
					        endif;
					        continue;
				        endif; ?>
				        <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
				        <dd<?php if (isset($_formatedOptionValue['full_view'])) : ?> class="truncated"<?php endif; ?>>
					        <?php echo $_formatedOptionValue['value'] ?>
					        <?php if (isset($_formatedOptionValue['full_view'])) : ?>
						        <div class="truncated_full_value">
							        <dl class="item-options">
								        <dt><?php echo $this->htmlEscape($_option['label']) . $_option['code'] ?></dt>
								        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
							        </dl>
						        </div>
					        <?php endif; ?>
				        </dd>
			        <?php else : ?>
				        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
				        <dd><?php echo $_formatedOptionValue['value'] ?></dd>
			        <?php endif; ?>
		        <?php endforeach; ?>
	        </dl>
        <?php endif; ?>
        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()): ?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
    </td>

    <td class="a-right">
        <span class="label"><?php echo $this->__('Qty') ?></span><?php echo $_item->getQty() ?>
    </td>

    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <span class="label"><?php echo $this->__('Price') . $this->helper('tax')->getIncExcTaxLabel(false) ?></span>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            <?php endif; ?>
        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
            <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
            </div>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>

    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <span class="label"><?php echo $this->__('Price') . $this->helper('tax')->getIncExcTaxLabel(true) ?></span>
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php $_productPrice = $_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item); ?>
                <?php echo $this->helper('checkout')->formatPrice($_productPrice); ?>
                <?php if($_item->getProduct()->getSpecialPrice() && $_productPrice < $_item->getProduct()->getPrice()): ?>
		            <?php
		            $productPrice = null;
		
		            if (Mage::helper('core')->isModuleEnabled('MindMagnet_Configurable') && $_item->getProductType() == 'configurable') {
			            $id = Mage::getModel('catalog/product')->getIdBySku($_item->getSku());
			            $productPrice = Mage::getModel('catalog/product')->load($id)->getPrice();
		            }
		            ?>
                    <span class="old-price"><span class="price"><?php echo $this->helper('checkout')->formatPrice($productPrice ?? $_item->getProduct()->getPrice()); ?></span></span>
                <?php endif; ?>
            <?php else: ?>
                <?php $_productPrice = $_incl - $_item->getWeeeTaxDisposition(); ?>
                <?php echo $this->helper('checkout')->formatPrice($_productPrice); ?>
                <?php if($_item->getProduct()->getSpecialPrice() && $_productPrice < $_item->getProduct()->getPrice()): ?>
		            <?php
		            $productPrice = null;
		
		            if (Mage::helper('core')->isModuleEnabled('MindMagnet_Configurable') && $_item->getProductType() == 'configurable') {
			            $id = Mage::getModel('catalog/product')->getIdBySku($_item->getSku());
			            $productPrice = Mage::getModel('catalog/product')->load($id)->getPrice();
		            }
		            ?>
                    <span class="old-price"><span class="price"><?php echo $this->helper('checkout')->formatPrice($productPrice ?? $_item->getProduct()->getPrice()); ?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
            <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
            </div>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>

    <!-- sub total starts here -->

    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <span class="label"><?php echo $this->__('Subtotal') . $this->helper('tax')->getIncExcTaxLabel(false) ?></span>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>
        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
            <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
            </div>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>

    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <span class="label"><?php echo $this->__('Subtotal') . $this->helper('tax')->getIncExcTaxLabel(true) ?></span>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
        <?php else: ?>
            <span class="cart-price">
        <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
            <?php endif; ?>
        </span>
        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
            <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
            </div>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </td>
    <?php endif; ?>
</tr>

<?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
	<?php if ($showCustom) : ?>
		<script>
					jQuery(function () {
						jQuery('#productpersonalized-<?php echo $_item->getId() ?>').responsiveSlides({
							auto: false,
							pager: false,
							nav: true,
							speed: 500,
							namespace: 'callbacks',
							before: function () {
							},
							after: function () {
							}
						});
						
						var Modal = (function() {
							var modalOpen = document.querySelector('[data-modal="open-<?php echo $_item->getId() ?>"]'),
								modalClose = document.querySelector('[data-modal="close-<?php echo $_item->getId() ?>"]'),
								modalWrapper = document.querySelector('[data-modal="wrapper-<?php echo $_item->getId() ?>"]');
							
							return {
								init: function() {
									this.open();
									this.close();
								},
								
								open: function() {
									modalOpen.onclick = function(e) {
										e.preventDefault();
										modalWrapper.classList.add('modal-opened');
									}
								},
								
								close: function() {
									modalClose.onclick = function(e) {
										e.preventDefault();
										modalWrapper.classList.remove('modal-opened');
									}
								}
							}
						}());
						Modal.init();
					});
		</script>
	<?php endif; ?>
<?php endif; ?>
