<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Options */
?>

<?php $options = $this->getOptionList(); ?>
<?php if ($options): ?>
<div class="truncated">
  <div class="truncated_full_value">
      <div class="item-options">
          <p><?php echo $this->__('Options Details'); ?></p>
          <dl>
              <?php foreach ($_options as $_option) : ?>
                  <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                  <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                  <dd><?php echo $_formatedOptionValue['value'] ?></dd>
              <?php endforeach; ?>
          </dl>
      </div>
  </div>
  <a href="#" onclick="return false;" class="details"><?php echo $this->__('View Details') ?></a>
</div>
<?php endif; ?>
