<?php
/**
 * Category left navigation
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php if (!Mage::registry('current_category')) return; ?>
<?php $_categories = $this->getCurrentChildCategories(); ?>
<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
<?php if ($_count): ?>
    <div class="filters-mobile-trigger on-mobile" data-dock=".block-layered-nav"><?php echo $this->__('Filter') ?></div>
    <div class="block block-layered-nav dock">
        <div class="block-title">
            <strong><span><?php echo $this->__('Browse By') ?></span></strong>
        </div>
        <div class="block-content">
            <dl id="narrow-by-list2">
                <dt><?php echo $this->__('Category') ?></dt>
                <dd>
                    <ol>
                        <?php foreach ($_categories as $_category): ?>
                            <?php if ($_category->getIsActive()): ?>
                                <li>
                                    <?php if ($this->isCategoryActive($_category)): ?>
                                        <?php echo $_item->getLabel() ?>
                                    <?php else: ?>
                                        <a href="<?php echo $this->getCategoryUrl($_category) ?>"><?php echo $this->escapeHtml($_category->getName()) ?></a>
                                    <?php endif; ?>
                                    <em><?php echo $_category->getProductCount() ?></em>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
