<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$_minicartImage = $this->getLayout()->getBlock('root') ? (int) ($this->getLayout()->getBlock('root')->getMinicartImage() ? : 2) : 2;

if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/personalized')->isEnabled() && Mage::helper('personalized/data')->isItemPersonalized($_item)) {
	$options    = $this->getOptionList();
	$helper     = Mage::helper('personalized/data');
	
	if ($_item->getProductType() == 'configurable') {
		foreach ($_item->getOrder()->getAllItems() as $item) {
			if ($item->getParentItemId() == $_item->getId()) {
				$productOptions = $item->getProductOptions();
				$additionalOption = $productOptions['additional_options'];
				$options = array_merge($options, $additionalOption);
			}
		}
	}
	
	$imageurl = $helper->getImageUrl($options);
	$counter  = 1;
	
	if (!count($imageurl)) {
		array_push($imageurl, $this->getProductThumbnail()->resize(50, 50));
	}
}

$customProductsId  = array();
$customProductsSku = array();

if (Mage::helper('core')->isModuleEnabled('Blugento_Customproduct')) {
	$customProductHelper = Mage::helper('blugento_customproduct');
	if ($customProductHelper->isEnabled()) {
		$customProductsId  = explode(',', $customProductHelper->getProductsById());
		$customProductsSku = explode(',', $customProductHelper->getProductsBySku());
	}
}
?>
<li class="item">
    <div class="edit-remove">
        <?php if ($isVisibleProduct): ?>
            <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Edit item')) ?>" class="btn-edit"><?php echo $this->__('Edit item')?></a>
        <?php endif; ?>
	    <?php if ($_item->getProduct()->getTypeId() != 'fontcolor' && (!in_array($_item->getProductId(), $customProductsId) && !in_array($_item->getSku(), $customProductsSku))) : ?>
	        <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>"
		        <?php if (Mage::helper('core')->isModuleEnabled('Blugento_AjaxCart') && Mage::helper('blugento_ajaxcart')->isEnabled() && Mage::helper('blugento_ajaxcart')->isCartDeleteEnabled()) : ?>
			        data-confirmdelete="<?php echo Mage::helper('blugento_ajaxcart')->isCartDeleteEnabled(); ?>"
		        <?php endif; ?>
		       class="btn-remove">
		        <?php echo $this->__('Remove This Item') ?>
	        </a>
	    <?php endif; ?>
    </div>
    <div class="product-details">

        <?php if ($_minicartImage != 2): ?>
	        <?php $textColor = Mage::getModel('catalog/product')->load($_item->getProduct()->getId()); ?>
            <?php if ($this->hasProductUrl()): ?>
                <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-cart product-image" style="border: none;">
	            <?php if (Mage::helper('core')->isModuleEnabled('Blugento_TextOptions') && $_item->getProduct()->getTypeId() == 'fontcolor') : ?>
		            <div class="font-color-box" style="width: 71px; height: 104px; background-color: <?php echo $textColor->getTextFontColor(); ?>"></div>
	            <?php else : ?>
		            <?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
			            <img src="<?php echo $imageurl[0]; ?>" style="width: 50px; height: 50px;" class="img-responsive" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
		            <?php else : ?>
                        <img src="<?php echo $this->getProductThumbnail()->resize(71, 104); ?>" width="71" height="104" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/>
		            <?php endif; ?>
	            <?php endif; ?>
		        </a>
            <?php else: ?>
                <span class="product-image product-cart">
	            <?php if (Mage::helper('core')->isModuleEnabled('Blugento_TextOptions') && $_item->getProduct()->getTypeId() == 'fontcolor') : ?>
		            <div class="font-color-box" style="width: 50px; height: 50px; background-color: <?php echo $textColor->getTextFontColor(); ?>"></div>
	            <?php else : ?>
		            <?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
			            <img src="<?php echo $imageurl[0]; ?>" style="width: 50px; height: 50px;" class="img-responsive" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
		            <?php else : ?>
                        <img src="<?php echo $this->getProductThumbnail()->resize(50, 50); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/>
                    <?php endif; ?>
		        <?php endif; ?>
		        </span>
            <?php endif; ?>
        <?php endif; ?>

        <div class="product-cart-details">
            <?php if ($_minicartImage != 2): ?>
                <p class="product-name product-name-first"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->escapeHtml($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
            <?php endif; ?>
            <p class="price-qty">
                <span><?php echo $this->getQty() ?></span><span> x </span>

                <?php if ($canApplyMsrp): ?>

                    <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>

                <?php else: ?>

                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <?php echo $this->__('Excl. Tax'); ?>:
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                            <br />
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                                <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                                <?php endforeach; ?>
                                </small>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                                <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                                <?php endforeach; ?>
                                </small>
                            <?php endif; ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endif; // Can apply MSRP ?>

                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <br /><?php echo $this->__('Incl. Tax'); ?>:
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <br />
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                                <?php endforeach; ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                                <?php endforeach; ?>
                            </small>
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)); ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
            <?php if ($_minicartImage != 1): ?>
                <p class="product-name"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->escapeHtml($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
            <?php endif; ?>
            <?php if ($_options = $this->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
	                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
	                    <?php if (Mage::helper('core')->isModuleEnabled('Milople_Personalized') && Mage::helper('personalized/data')->isItemPersonalized($_item)) : ?>
		                    <?php $text_object = 1; ?>
		                    <?php if (isset($_option['code']) && ($_option['code'] == 'milople_imageurl' || $_option['code'] == 'milople_row_images' || $_option['code'] == 'text' . $text_object || $_option['code'] == 'text' . $text_object . '_font_family' || $_option['code'] == 'text' . $text_object . '_font_size')) :
			                    if ($_option['code'] == 'text' . $text_object . '_font_size') :
				                    $text_object++;
			                    endif;
			                    continue;
		                    endif; ?>
		                    <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
		                    <dd<?php if (isset($_formatedOptionValue['full_view'])) : ?> class="truncated"<?php endif; ?>>
			                    <?php echo $_formatedOptionValue['value'] ?>
			                    <?php if (isset($_formatedOptionValue['full_view'])) : ?>
				                    <div class="truncated_full_value">
					                    <dl class="item-options">
						                    <dt><?php echo $this->htmlEscape($_option['label']) . $_option['code'] ?></dt>
						                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
					                    </dl>
				                    </div>
			                    <?php endif; ?>
		                    </dd>
	                    <?php else : ?>
		                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
		                    <dd><?php echo $_formatedOptionValue['value'] ?></dd>
	                    <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
</li>
