<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
$_productListPaginationPager = (int) ($this->getLayout()->getBlock('root')->getProductListPaginationPager() ?: 2);
?>
<?php if ($this->getCollection()->getSize()): ?>

    <?php if ($this->getUseContainer()): ?>
    <div class="pager pager--no-toolbar">
    <?php endif; ?>

    <?php if ($this->getShowAmounts()): ?>
    <p class="amount">
        <?php if ($this->getLastPageNum() > 1): ?>
            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </p>
    <?php endif; ?>

    <?php if ($this->getShowPerPage()): ?>
    <div class="limiter">
        <label><?php echo $this->__('Show') ?></label><!--
        --><select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
            <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if ($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
        </select><!--
        --><label><?php echo $this->__('per page') ?></label>
    </div>
    <?php endif; ?>

    <?php if ($this->getLastPageNum() > 1): ?>
    <div class="pages">
        <strong><?php echo $this->__('Page:') ?></strong>
        <ol>
            <?php if ($_productListPaginationPager == 1): ?>
                <?php if (!$this->isFirstPage()): ?>
                    <?php if ($this->getFramePages($start)): ?>
                        <li class="first-page"><a href="<?php echo $this->getFirstPageUrl() ?>"><span>&laquo;</span></a></li>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
            <?php if (!$this->isFirstPage()): ?>
                <li>
                    <a rel="prev"
                       class="previous<?php if (!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif; ?>"
                       href="<?php echo $this->getPreviousPageUrl() ?>"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>">
                        <?php echo $this->getAnchorTextForPrevious() ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->canShowFirst()): ?>
                <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <?php endif; ?>

            <?php if ($this->canShowPreviousJump()): ?>
                <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
            <?php endif; ?>

            <?php foreach ($this->getFramePages() as $_page): ?>
                <?php if ($this->isPageCurrent($_page)): ?>
                    <li class="current"><?php echo $_page ?></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if ($this->canShowNextJump()): ?>
                <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
            <?php endif; ?>

            <?php if ($this->canShowLast()): ?>
              <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
            <?php endif; ?>

            <?php if (!$this->isLastPage()): ?>
                <li>
                    <a rel="next" class="next<?php if (!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Next')) ?>">
                        <?php echo $this->getAnchorTextForNext() ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($_productListPaginationPager == 1): ?>
                <?php if (!$this->isLastPage()): ?>
                    <?php if ($this->getFramePages($end)): ?>
                        <li class="last-page"><a href="<?php echo $this->getLastPageUrl() ?>"><span>&raquo;</span></a></li>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </ol>

    </div>
    <?php endif; ?>

    <?php if ($this->getUseContainer()): ?>
    </div>
    <?php endif; ?>

<?php endif; ?>
