<?php
$_enabledGdpr = Mage::getStoreConfig('blugento_gdpruserdata/general/enabled');
?>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<div class="row">
    <div class="col-6 col-xs-12 contact-col-1">
        <form action="<?php if (Mage::helper('core')->isModuleEnabled('Magecomp_Recaptcha') && $this->helper('recaptcha')->showOnContact()): ?><?php else: ?><?php echo $this->getFormAction(); ?><?php endif; ?>" id="contactForm" method="post">
            <div class="fieldset">
                <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
                <ul class="form-list">
                    <li>
                        <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                        <div class="input-box">
                            <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                        </div>
                    </li>
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                        <div class="input-box">
                            <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                        </div>
                    </li>
                    <li>
                        <label for="area_of_activity" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Area of Activity') ?></label>
                        <div class="input-box">
                            <input name="area_of_activity" id="area_of_activity" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Area of Activity')) ?>" value="" class="input-text required-entry" type="text" />
                        </div>
                    </li>
                    <li>
                        <label for="telephone" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                        <div class="input-box">
                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="required-entry input-text validate-digits" type="text" />
                        </div>
                    </li>
                    <li>
                        <label for="comment"><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="input-text" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                    <?php if(Mage::helper('core')->isModuleEnabled('Blugento_GdprInformConsent')): ?>
                        <?php if ($_enabledGdpr == 1): ?>
                            <div class="gdpr-conditions">
                                <?php if (Mage::getStoreConfig('blugento_gdpruserdata/consent/read_more')): ?>
                                    <div class="content-popup-text show-less">
                                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blugento-contact-gdpr-acknowledgement-ro')->toHtml(); ?>
                                        <a href="#popup-conditions" class="show-more"><?php echo $this->__('[Show]') ?></a>
                                    </div>
                                    <script>
                                        (function($) {
                                            $('.content-popup-text .show-more').on('click', function() {
                                                $(this).parent().removeClass('show-less');
                                                $(this).remove();
                                            });
                                        })(jQuery);
                                    </script>
                                <?php else: ?>
                                    <div class="content-popup-text">
                                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blugento-contact-gdpr-acknowledgement-ro')->toHtml(); ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </ul>
            </div>
            <?php if (Mage::helper('core')->isModuleEnabled('Magecomp_Recaptcha') && $this->helper('recaptcha')->showOnContact()): ?>
                <div class="no-display">
                    <input type="text" name="noSpam" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('No Spam')) ?>" id="no-spam-contact" class="input-text no-display required-entry" />
                </div>
            <?php endif; ?>
            <div class="buttons-set">
                <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" name="send" id="g-recaptcha-contact" class="g-recaptcha-contact button disabled" data-badge="bottomleft" data-size="invisible"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            </div>
        </form>
    </div>
    <div class="col-6 col-xs-12 contact-col-2">
        <?php echo $this->getChildHtml('info') ?>
    </div>
</div>
<script>
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
</script>
<?php if (Mage::helper('core')->isModuleEnabled('Magecomp_Recaptcha') && $this->helper('recaptcha')->showOnContact()): ?>
    <script>
        // Prevent form to submit if hidden input has value
        jQuery('#contactForm').submit(function(e) {
            if (jQuery('#no-spam-contact').val() !== '') {
                e.preventDefault();

                window.history.back();
            }
        });

        function onSubmitContact(token) {
            setTimeout(function(){
                jQuery('.g-recaptcha-contact').attr('data-token', token);

                if (jQuery('#no-spam').val() === '' || jQuery('#no-spam').val() === undefined) {
                    return new Promise(function (resolve, reject) {
                        var dataForm = new VarienForm('form-validate');
                        var tokenHash = jQuery('.g-recaptcha-contact').attr('data-token');

                        if (tokenHash && tokenHash.length > 100) {
                            jQuery('#no-spam').removeClass('required-entry');

                            if (dataForm.validator && dataForm.validator.validate()){
                                jQuery('#contactForm').attr('action', '<?php echo $this->getFormAction() ?>');

                                document.getElementById("contactForm").submit();
                            }
                        }
                    });
                } else {
                    window.history.back();
                }
            }, 500);
        }

        // Check if captcha container have loaded class, if not than captcha will be loaded
        function loadCaptchaContact() {
            // Fix for google recaptcha from 18 June
            if ("NodeList" in window) {
                if (!NodeList.prototype.each && NodeList.prototype.forEach) {
                    NodeList.prototype.each = NodeList.prototype.forEach;
                }
            }

            if (!jQuery('.captcha_container_contact').length) {
                jQuery('#g-recaptcha-contact').addClass('captcha_container_contact');
                var captchaContainer = null;
                var loadCaptchaContactFunction = function() {
                    captchaContainer = grecaptcha.render('g-recaptcha-contact', {
                        'sitekey': '<?php echo $this->helper('recaptcha')->getKey(); ?>',
                        'callback': onSubmitContact
                    });
                };

                loadCaptchaContactFunction();
            }
        };

        // Once user insert a value, loadCaptchaContent will be called
        jQuery('#contactForm input, #contactForm textarea').each(function(e) {
            jQuery(this).on('change keyup blur input', function(e) {
                loadCaptchaContact();
            });
        });


        jQuery('.g-recaptcha-contact').on('click', function(e) {
            onSubmitContact();
        });
    </script>
    <script src="https://www.google.com/recaptcha/api.js?onload=loadCaptchaContactFunction&render=explicit" async defer></script>

<?php endif; ?>