<?php
/**
 * @see Mage_Paypal_Block_Logo
 */
?>
<div class="block block-generic">
    <div class="block-title">
        <strong>
            <span>PayPal</span>
        </strong>
    </div>
    <div class="block-content">
        <div class="paypal-logo">
            <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;">
                <img src="https://www.paypalobjects.com/webstatic/mktg/logo/bdg_now_accepting_pp_2line_w.png" border="0" alt="Now accepting PayPal"
            /></a>
            <div class="actions">
                <a href="https://www.paypal.com/webapps/mpp/how-paypal-works" rel="noopener" target="_blank">How PayPal Works</a>
            </div>
        </div>
    </div>
</div>
