<?php
    $_disableCheckbox = Mage::getStoreConfig('blugento_gdpruserdata/consent/notification_consent');
?>
<?php if(Mage::helper('core')->isModuleEnabled('Blugento_GdprInformConsent')): ?>
    <div class="gdpr-conditions">
        <div class="<?php if ($_disableCheckbox): ?>checkbox-hidden<?php endif; ?>">
            <input name="gdpr_consent" id="gdpr-conditions-consent" <?php if ($_disableCheckbox): ?>checked<?php endif; ?> type="checkbox" class="checkbox required-entry">
            <label for="gdpr-conditions-consent" style="float:none;" class="required">
                <em>*</em>
                <?php echo $this->__('I agree with the processing of personal data under the ') ?>
                <a class="privacy-policy-show-popup" href="#"><?php echo $this->__('Privacy Policy') ?></a>
                <div id="privacy-policy-popup" class="modal privacy-policy-popup">
                    <div class="sub-container">
                        <div class="content">
                            <div class="privacy-policy-popup-content">
                                <div><?php echo $this->getPrivacyPolicyContent(); ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </label>
            <div class="validation-advice no-display-field"><?php echo $this->__('This is a required field.') ?></div>
        </div>
        <?php if (Mage::getStoreConfig('blugento_gdpruserdata/consent/read_more')): ?>
            <div class="<?php if ($_disableCheckbox): ?>checkbox-disabled<?php endif; ?> content-popup-text show-less">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blugento-checkout-gdpr-acknowledgement')->toHtml(); ?>
                <a href="#popup-conditions" class="show-more"><?php echo $this->__('[Show]') ?></a>
            </div>
            <script>
                (function($) {
                    $('.content-popup-text .show-more').on('click', function() {
                        $(this).parent().removeClass('show-less');
                        $(this).remove();
                    });
                })(jQuery);
            </script>
        <?php else: ?>
            <div class="content-popup-text">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blugento-checkout-gdpr-acknowledgement')->toHtml(); ?>
            </div>
        <?php endif; ?>
        <script>
            (function($) {
                <?php if(!$_disableCheckbox || $_disableCheckbox == '0'): ?>
                    console.log('validating');
                    if(!$('#gdpr-conditions-consent').is(':checked')) {
                        $('.btn-checkout').wrap('<div class="btn-checkout-wrap"></div>');
                        $('.btn-checkout-wrap').append('<span class="btn-checkout-overlay"></span>');
                    }

                    $('#gdpr-conditions-consent').on('change', function() {
                        if($('#gdpr-conditions-consent').is(':checked')) {
                            $('.gdpr-conditions .validation-advice').hide();
                            $('.btn-checkout-overlay').hide();
                        } else {
                            $('.gdpr-conditions .validation-advice').show();
                            $('.btn-checkout-overlay').show();
                        }
                    });

                    $('.btn-checkout-overlay').on('click', function() {
                        $('.gdpr-conditions .validation-advice').show();
                    });
                <?php endif; ?>

                $('.privacy-policy-show-popup').on('click', function() {
                    $.magnificPopup.open({
                        items: {
                            src: '#privacy-policy-popup'
                        },
                        type: 'inline'
                    },0);
                });
            })(jQuery);
        </script>
    </div>
<?php endif; ?>