<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */

$_dimHelper = Mage::helper('configurableswatches/swatchdimensions');
$_swatchInnerWidth = $_dimHelper->getInnerWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchInnerHeight = $_dimHelper->getInnerHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchOuterWidth = $_dimHelper->getOuterWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_swatchOuterHeight = $_dimHelper->getOuterHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LAYER);
$_filterNofollow = Mage::getStoreConfig('blugento_seoenhancements/enhancements_group/add_nofollow_on_filters_link');
?>

<ol class="configurable-swatch-list clearfix">
    <?php foreach ($this->getItems() as $_item): ?>
        <?php
        $_hasItems = ($_item->getCount() > 0);
        $_label = $_item->getLabel();
        $_swatchUrl = Mage::helper('configurableswatches/productimg')->getGlobalSwatchUrl($_item, $_label, $_swatchInnerWidth, $_swatchInnerHeight);
        $_swatchUrl2x = Mage::helper('configurableswatches/productimg')->getGlobalSwatchUrl($_item, $_label, $_swatchInnerWidth * 2, $_swatchInnerHeight * 2);
        $_hasImage = (!empty($_swatchUrl));
        $_linkClass = 'swatch-link' . (($_hasImage) ? ' has-image' : ' has-no-image');
        ?>
        <li>
            <?php if ($_hasItems): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" <?php if ($_filterNofollow): ?>rel="nofollow"<?php endif; ?> class="<?php echo $_linkClass ?>">
            <?php else: ?>
                <span class="<?php echo $_linkClass ?>">
            <?php endif; ?>
                <span class="swatch-label">
                    <?php if ($_hasImage): ?>
                        <img src="<?php echo $_swatchUrl ?>" srcset="<?php echo $_swatchUrl; ?> 1x, <?php echo $_swatchUrl2x; ?> 2x" alt="<?php echo $_label ?>" title="<?php echo $_label ?>" width="<?php echo $_swatchInnerWidth ?>" height="<?php echo $_swatchInnerHeight ?>" />
                    <?php else: ?>
                        <span><?php echo $_label ?></span>
                    <?php endif; ?>
                </span>
            <?php if ($_hasItems): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <?php if ($this->shouldDisplayProductCount()): ?>
            <em>(<?php echo $_item->getCount() ?>)</em>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ol>
