<?php
$analyticsCategoryId = Mage::getStoreConfig('cadence_fbpixel/analytics/category');
$categories = Mage::getModel('gdprcookies/system_config_source_categories')->toOptionArray();
foreach ($categories as $category) {
    if ($category['value'] == $analyticsCategoryId) {
        $analyticsCategory = strtolower($category['label']);
    }
}
$analyticsCategory = str_replace('analytics', 'statistics', $analyticsCategory);
?>
<?php
$helper = Mage::helper("cadence_fbpixel");
if (!$helper->isVisitorPixelEnabled()) {
    return;
}
$id = $helper->getVisitorPixelId();
?>
<!-- Facebook Pixel Code -->
<script>
    !function (f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function () {
            n.callMethod ?
                n.callMethod.apply(n, arguments) : n.queue.push(arguments)
        };
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s)
    }(window,
        document, 'script', '//connect.facebook.net/en_US/fbevents.js');

    (function($) {
        $(document).ready(function() {
            function facebookPixelFunctions() {
                fbq('init', '<?php echo $id ?>');
                fbq('track', "PageView", { 'external_id': '<?php echo Mage::getSingleton('core/session')->getFbExternalId() ?>' }
                <?php if ($eventId = $helper->getEventId('PageView')): ?>
                    ,{
                        'eventID': '<?php echo $eventId ?>'
                    }
                <?php endif; ?>
                );
            };

            if (!$('body').hasClass('gdpr-enabled') || '<?php echo $analyticsCategoryId ?>' == '1' || '<?php echo Mage::getSingleton('core/cookie')->get($analyticsCategory) ?>' == 'yes') {
                facebookPixelFunctions();
            } else {
                // Accept only selected cookies
                $('#accept-selected-cookies').on('click', function(e) {
                    if ($('#<?php echo $analyticsCategory ?>').is(':checked') || $('#<?php echo $analyticsCategory ?>').is('[readonly]')) {
                        facebookPixelFunctions();
                    }
                });

                // Accept all cookies
                $('#accept-all-cookies').on('click', function(e) {
                    facebookPixelFunctions();
                });

                if ('<?php echo $analyticsCategory ?>' == 'necessary') {
                    facebookPixelFunctions();
                }
            }
        });
    })(jQuery);
</script>
<!-- <noscript><img height="1" width="1" style="display:none"
                src="https://www.facebook.com/tr?id=<?php // echo $id ?>&ev=PageView&noscript=1"
    /></noscript> -->
<!-- End Facebook Pixel Code -->
