<?php
$helper = $this->helper('customer');
?>
<div class="mini-account">
    <i></i>
    <ul class="list list--links list--horizontal list--dividers">
        <?php if ($helper->isLoggedIn()): ?>
        <li class="list__item">
            <a href="<?php echo $helper->getAccountUrl() ?>" rel="nofollow" title="<?php echo $this->__('My Account'); ?>"><?php echo $this->__('My Account'); ?></a>
        </li>
        <li class="list__item">
            <a class="logout-btn" href="<?php echo $helper->getLogoutUrl(); ?>" rel="nofollow" title="<?php echo $this->__('Log Out'); ?>"><?php echo $this->__('Log Out'); ?></a>
        </li>
        <?php else: ?>
        <li class="list__item">
            <a id="noaccount" href="<?php echo $helper->getRegisterUrl() ?>" rel="nofollow" title="<?php echo $this->__('Register'); ?>"><?php echo $this->__('Register'); ?></a>
        </li>
        <li class="list__item">
            <a class="login-btn" href="<?php echo $helper->getAccountUrl() ?>" rel="nofollow" title="<?php echo $this->__('Log In'); ?>"><?php echo $this->__('Log In'); ?></a>
        </li>
        <?php endif; ?>
    </ul>
</div>
