<?php
$_product = $this->getProduct();
if (
    Mage::helper('configurableswatches')->isEnabled()
    && $_product && $_product->getId()
    && ($_attrValues = $_product->getListSwatchAttrValues())
    && count($_attrValues) > 0
):
    $_swatchAttribute = Mage::helper('configurableswatches/productlist')->getSwatchAttribute();

    $_dimHelper = Mage::helper('configurableswatches/swatchdimensions');
    $_swatchInnerWidth = $_dimHelper->getInnerWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LISTING);
    $_swatchInnerHeight = $_dimHelper->getInnerHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LISTING);
    $_swatchOuterWidth = $_dimHelper->getOuterWidth(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LISTING);
    $_swatchOuterHeight = $_dimHelper->getOuterHeight(Mage_ConfigurableSwatches_Helper_Swatchdimensions::AREA_LISTING);

    $_optionIds = array_keys($_attrValues);

    if (Mage::registry('blugento_swatches_collection')) {
        $_swatchesData = Mage::registry('blugento_swatches_collection');
    } else {
        $_swatchesData = Mage::getModel('blugento_swatches/swatches')->getCollection();
    }

    ?>
    <ul class="configurable-swatch-list configurable-swatch-<?php echo $_swatchAttribute->getAttributeCode() ?> blugento-swatches clearfix">
        <?php foreach ($_attrValues as $_optionValue => $_optionLabel): ?>
            <?php
            $_swatchData = $_swatchesData->getItemByColumnValue('option_id', $_optionValue);
            $_mode = $_swatchData->getMode();
            $_image = $_swatchData->getImageName();
            $_color = $_swatchData->getColor();
            $_getMedia = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
            $_optionCode = Mage::helper('configurableswatches')->getHyphenatedString($_optionLabel);
            $_swatchUrl = Mage::helper('configurableswatches/productimg')->getSwatchUrl($_product, $_optionLabel, $_swatchInnerWidth, $_swatchInnerHeight, $_swatchType);
            $_liClasses = array();
            $_aClass = 'swatch-link swatch-link-' . $_swatchAttribute->getId();
            if ($_mode == 2 && $_image) {
                if ($_swatchType == 'media') {
                    $_liClasses[] = 'is-media';
                }
                $_aClass .= ' has-image';
            }
            if (Mage::helper('configurableswatches/productlist')->swatchMatchesFilter($_optionValue)) {
                $_liClasses[] = 'filter-match';
            }
            $_liClass = (!empty($_liClasses)) ? ' ' . implode(' ', $_liClasses) : '';
            ?>
            <li class="option-<?php echo $_optionCode ?><?php echo $_liClass ?>" data-product-id="<?php echo $_product->getId() ?>" data-option-label="<?php echo $_optionLabel ?>">
                <a href="javascript:void(0)" name="<?php echo $_optionCode ?>" data-product-value="<?php echo $_optionValue ?>" class="<?php echo $_aClass ?>" title="<?php echo $_optionLabel ?>">
                    <?php if ($_mode == 2 && $_image): ?>
                        <span class="swatch-label">
                            <img src="<?php echo $_getMedia,$_image ?>" alt="<?php echo $_optionLabel ?>" width="<?php echo $_swatchInnerWidth - 2?>" height="<?php echo $_swatchInnerHeight - 2?>" />
                        </span>
                    <?php else: ?>
                        <?php if (Mage::getStoreConfig('configswatches/blugento_swatches/display_label') || ($_mode == 2 && $_image)): ?>
                            <span class="swatch-label with-label" style="background-color: #<?php echo $_color ?>; line-height: <?php echo $_swatchInnerHeight ?>px; min-width: <?php echo $_swatchInnerWidth ?>px;">
                                <span style="height: <?php echo $_swatchInnerWidth ?>px;"><?php echo $_optionLabel ?></span>
                            </span>
                        <?php else: ?>
                            <?php if ($_color == ''): ?>
                                <span class="swatch-label no-color" style="height: <?php echo $_swatchInnerHeight ?>px; line-height: <?php echo $_swatchInnerHeight ?>px; min-width: <?php echo $_swatchInnerWidth ?>px;">
                                    <span><?php echo $_option->label ?></span>
                                  </span>
                            <?php else: ?>
                                <span class="swatch-label no-label" style="background-color: #<?php echo $_color ?>; height: <?php echo $_swatchInnerHeight ?>px; width: <?php echo $_swatchInnerWidth ?>px;"></span>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php
endif;
