<?php
/**
 * Blugento Billing Attributes
 * Helper Class
 *
 * Copyright (C) 2015-2016 Blugento <contact@blugento.com>
 * LICENSE: GNU General Public License for more details <http://opensource.org/licenses/gpl-license.php>
 *
 * @package Blugento_Billing
 * @author Simona Trifan <simona.plesuvu@mindmagnetsoftware.com>
 * @link http://www.blugento.com
 */
?>

<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */

$attributePurchaseType = Mage::getSingleton('eav/config')->getAttribute('customer_address', 'blugento_purchase_type');
$attributePurchaseTypeOptions = $attributePurchaseType->getSource()->getAllOptions(false);
$attributePf = 0;
$attributePj = 0;
$selectedPurchaseType = $attributePurchaseTypeOptions ? $attributePurchaseTypeOptions[0]['value'] : 0;
$purchaseType = $this->getAddress()->getBlugentoPurchaseType();
if (!$purchaseType) {
    $purchaseType = $attributePurchaseTypeOptions ? $attributePurchaseTypeOptions[0]['value'] : 0;
}
/* @var Blugento_Billing_Helper_Data $billHelper */
$billHelper = Mage::helper('blugento_billing');
?>

<?php if($this->getTitle()): ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle() ?></h1>
    </div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getNameBlockHtml() ?>
            </li>
            <li class="wide chose-entity">
                <?php foreach($attributePurchaseTypeOptions as $option) :
                    if ($option['label'] == 'Personal Purchase') {
                        $attributePf = $option['value'];
                    } else {
                        $attributePj = $option['value'];
                    } ?>
                    <input type="radio" name="blugento_purchase_type" id="blugento_purchase_type_<?php echo $option['value']; ?>"
                           value="<?php echo $option['value']; ?>"
                        <?php if ($purchaseType == $option['value']) : $selectedPurchaseType = $option['value']; ?> checked="checked"<?php endif; ?>
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__($option['label'])) ?>"
                           class="radio"
                           onclick="displayPurchaseType(this)"/>
                    <label for="blugento_purchase_type_<?php echo $option['value']; ?>"><?php echo $this->__($option['label']); ?></label>
                <?php endforeach; ?>
            </li>

            <?php if ($billHelper->getAttributeClass('company')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePj; ?>" <?php if ($purchaseType != $attributePj) : ?>style="display: none;"<?php endif; ?>>
                    <label for="company" class="required">
                        <?php echo $this->__('Company') ?>
                        <?php if ($billHelper->getAttributeClass('company') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               name="company"
                               id="company"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                               class="input-text conditional-required-pj <?php echo $billHelper->getAttributeClass('company') ?>"
                        />
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($billHelper->getAttributeClass('blugento_customer_reg_no')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePj; ?>" <?php if ($purchaseType != $attributePj) : ?>style="display: none;"<?php endif; ?>>
                    <label for="blugento_customer_reg_no" class="<?php if ($billHelper->getAttributeClass('blugento_customer_reg_no') == 'required-entry') echo 'class="required"'; ?>">
                        <?php echo $this->__('Company Registration Number') ?>
                        <?php if ($billHelper->getAttributeClass('blugento_customer_reg_no') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               name="blugento_customer_reg_no"
                               id="blugento_customer_reg_no"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company Registration Number')) ?>"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getBlugentoCustomerRegNo()) ?>"
                               class="input-text <?php echo $billHelper->getAttributeClass('blugento_customer_reg_no') ?>"
                        />
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($billHelper->getAttributeClass('vat_id')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePj; ?>" <?php if ($purchaseType != $attributePj) : ?>style="display: none;"<?php endif; ?>>
                    <label for="vat_id" class="<?php if ($billHelper->getAttributeClass('vat_id') == 'required-entry') echo 'class="required"'; ?>">
                        <?php echo $this->__('VAT Number') ?>
                        <?php if ($billHelper->getAttributeClass('vat_id') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               name="vat_id"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>"
                               id="vat_id"
                               class="input-text conditional-required-pj <?php echo $billHelper->getAttributeClass('vat_id') ?>"
                        />
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($billHelper->getAttributeClass('blugento_customer_iban')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePj; ?>" <?php if ($purchaseType != $attributePj) : ?>style="display: none;"<?php endif; ?>>
                    <label for="blugento_customer_iban" class="<?php if ($billHelper->getAttributeClass('blugento_customer_iban') == 'required-entry') echo 'class="required"'; ?>">
                        <?php echo $this->__('IBAN') ?>
                        <?php if ($billHelper->getAttributeClass('blugento_customer_iban') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               name="blugento_customer_iban"
                               id="blugento_customer_iban"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('IBAN')) ?>"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getBlugentoCustomerIban()) ?>"
                               class="input-text <?php echo $billHelper->getAttributeClass('blugento_customer_iban') ?>"
                        />
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($billHelper->getAttributeClass('blugento_customer_headquarter')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePj; ?>" <?php if ($purchaseType != $attributePj) : ?>style="display: none;"<?php endif; ?>>
                    <label for="blugento_customer_headquarter" class="<?php if ($billHelper->getAttributeClass('blugento_customer_headquarter') == 'required-entry') echo 'class="required"'; ?>">
                        <?php echo $this->__('Headquarter') ?>
                        <?php if ($billHelper->getAttributeClass('blugento_customer_headquarter') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               name="blugento_customer_headquarter"
                               id="blugento_customer_headquarter"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Headquarter')) ?>"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getBlugentoCustomerHeadquarter()) ?>"
                               class="input-text <?php echo $billHelper->getAttributeClass('blugento_customer_headquarter') ?>"
                        />
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($billHelper->getAttributeClass('blugento_customer_bank')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePj; ?>" <?php if ($purchaseType != $attributePj) : ?>style="display: none;"<?php endif; ?>>
                    <label for="blugento_customer_bank" class="<?php if ($billHelper->getAttributeClass('blugento_customer_bank') == 'required-entry') echo 'class="required"'; ?>">
                        <?php echo $this->__('Bank Name') ?>
                        <?php if ($billHelper->getAttributeClass('blugento_customer_bank') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input type="text"
                               name="blugento_customer_bank"
                               id="blugento_customer_bank"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Bank Name')) ?>"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getBlugentoCustomerBank()) ?>"
                               class="input-text <?php echo $billHelper->getAttributeClass('blugento_customer_bank') ?>"
                        />
                    </div>
                </li>
            <?php endif; ?>

            <?php if ($billHelper->getAttributeClass('blugento_customer_cnp')): ?>
                <li class="wide blugento-purchase-type blugento-purchase-type-<?php echo $attributePf; ?>" <?php if ($purchaseType != $attributePf): ?>style="display: none;"<?php endif; ?>>
                    <label for="blugento_customer_cnp" class="<?php if ($billHelper->getAttributeClass('blugento_customer_cnp') == 'required-entry') echo 'class="required"'; ?>">
                        <?php echo $this->__('CNP') ?>
                        <?php if ($billHelper->getAttributeClass('blugento_customer_cnp') == 'required-entry'): ?> <em>*</em> <?php endif; ?>
                    </label>
                    <div class="input-box">
                        <input
                            type="text"
                            name="blugento_customer_cnp"
                            id="blugento_customer_cnp"
                            maxlength="13"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('CNP')) ?>"
                            value="<?php echo $this->escapeHtml($this->getAddress()->getBlugentoCustomerCnp()) ?>"
                            class="input-text <?php echo $billHelper->getAttributeClass('blugento_customer_cnp') ?>"                        />
                    </div>
                </li>
            <?php endif; ?>

            <li class="fields">
                <div class="field">
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                    </div>
                </div>
                <div class="field">
                    <label for="fax"><?php echo $this->__('Fax') ?></label>
                    <div class="input-box">
                        <input type="text" name="fax" id="fax" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <ul class="form-list">
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>

            <?php if ($billHelper->displayRegionBeforeCity()): ?>
                <div class="field">
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                            //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </div>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                </li>
            <?php else: ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                        </div>
                    </div>
                </li>
            <?php endif; ?>

            <li class="fields">
                <div class="field">
                    <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </li>
            <li<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?php echo $this->__('Default Billing Address') ?></strong>
                <?php else: ?>
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Billing Address')) ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                <?php endif; ?>
            </li>
            <li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php else: ?>
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Use as My Default Shipping Address')) ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                <?php endif; ?>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button data-action="save-customer-address" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Address')) ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>
    <?php echo $this->getBlockHtml('formkey') ?>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

    Validation.add('conditional-required-pj', 'This is a required field.', function(v) {
        var ch = $('blugento_purchase_type_<?php echo $attributePj; ?>').checked;
        if (ch) {
            return ( (v != "none") && (v != null) && (v.length != 0));
        }
        return true;
    });

    function displayPurchaseType(obj) {
        $$('.blugento-purchase-type').invoke('hide');
        $$('.blugento-purchase-type-' + $(obj).getValue()).invoke('show');
    }

    displayPurchaseType('blugento_purchase_type_<?php echo $selectedPurchaseType; ?>');
    //]]>
</script>

<?php if (Mage::helper('core')->isModuleEnabled('Eadesigndev_Romcity')): ?>
    <script type="text/javascript">
        //<![CDATA[
        CITIES_ACTION = "<?php echo $this->getUrl('citydropdown/index/cities'); ?>";

        var normalImput = '<input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />'

        document.observe("dom:loaded", function() {
            <?php if($this->getAddress()->getRegionId()): ?>
            var action = CITIES_ACTION;
            var selectCountry = $('country').value;
            var stateId = $('region_id').value;
            var selectedCity = '<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>';
            getAjaxReqestCustomer(action, selectCountry, stateId, normalImput,selectedCity)
            //$('city').setValue('<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>');
            <?php endif?>
        });

        Event.observe($('region_id'), 'change', function (event) {
            var selectedCity = false;
            var action = CITIES_ACTION;
            var selectCountry = $('country').value;
            var stateId = $('region_id').value;
            getAjaxReqestCustomer(action, selectCountry, stateId, normalImput,selectedCity)
        });
        //]]>
    </script>
<?php endif; ?>