<section>
    <h2>Headings</h2>
    <h1>Heading 1</h1>
    <h2>Heading 2</h2>
    <h3>Heading 3</h3>
    <h4>Heading 4</h4>
    <h5>Heading 5</h5>
    <h6>Heading 6</h6>
</section>
<section>
<section>
    <h2>Blockquotes</h2>
    <blockquote cite="http://www.worldwildlife.org/who/index.html"><i>For 50 years, <abbr title="World Health Organization">WHO</abbr> has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</i>
        <small>Author</small> &mdash; <cite>Source</cite>
    </blockquote>
</section>
<section>
    <h2>Tables</h2>
    <table>
        <tbody>
            <tr>
                <th>Number</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Points</th>
            </tr>
            <tr>
                <td>1</td>
                <td>Eve</td>
                <td>Jackson</td>
                <td>94</td>
            </tr>
            <tr>
                <td>2</td>
                <td>John</td>
                <td>Doe</td>
                <td>80</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Adam</td>
                <td>Johnson</td>
                <td>67</td>
            </tr>
            <tr>
                <td>4</td>
                <td>Jill</td>
                <td>Smith</td>
                <td>50</td>
            </tr>
        </tbody>
    </table>
</section>
<section>
    <h2>Lists</h2>
    <div class="row">
        <div class="col-3 col-sm-12">
            <ul>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
            </ul>
        </div>
        <div class="col-3 col-sm-12">
            <ul class="circle">
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
            </ul>
        </div>
        <div class="col-3 col-sm-12">
            <ol>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
            </ol>
        </div>
        <div class="col-3 col-sm-12">
            <ol class="letter">
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
                <li>Lorem ipsum dolor sit amet, consectetur adipisicing</li>
            </ol>
        </div>
    </div>
</section>
<section>
    <h2>Buttons</h2>
    <button class="button btn-primary btn-small"><span>Primary small button</span></button>
    <br><br>
    <button class="button"><span><span>Default button</span></span></button>
    <br><br>
    <button class="button btn-primary"><span><span>Primary button</span></span></button>
    <br><br>
    <button class="button btn-big"><span><span>Big default button</span></span></button>
    <br><br>
</section>
<section>
    <h2>Addresses</h2>
    <address>
        <strong>Company</strong><br>
        PO Box 77899<br>
        Vancouver, WA 23456<br>
        USA<br>
    </address>
</section>
<section>
<h2>Miscellaneous</h2>
<aside class="col-3 col-md-12">
    <h4>Lorem ipsum</h4>
    <p><a href="http://www.lipsum.com" rel="noopener" target="_blank">Lorem ipsum</a> dolor sit amet, consectetur adipiscing elit. Mauris eget ultrices nunc. <strong>Sed elit lorem, faucibus sed urna nec, scelerisque sodales nulla.</strong> Praesent sagittis arcu enim, vel efficitur ex mattis maximus. <em>Quisque egestas orci sem</em>, vitae laoreet tellus faucibus at.</p>
</aside>
<section class="col-md-12 col-9">
    <h4>Lorem ipsum</h4>
    <div class="row">
        <article class="col-sm-12 col-8">
            <p><i>Praesent iaculis lacus sed neque suscipit fringilla. Nunc vulputate et purus vel imperdiet.</i> Curabitur sed arcu sit amet eros auctor interdum. Duis eu neque posuere, ultrices magna nec, commodo nisl. Pellentesque ultricies ex nec ligula aliquet suscipit. Nam faucibus elit tortor, eu laoreet ipsum interdum in. Etiam consequat sollicitudin iaculis. Integer tincidunt rhoncus fermentum. <b>Vivamus a quam non eros bibendum hendrerit nec sit amet tortor.</b> Pellentesque venenatis enim a enim lobortis ullamcorper. 
            <p>Vestibulum elementum porta diam, nec finibus ex auctor faucibus. Sed eu lacus porta, ultrices neque nec, ullamcorper erat. Nulla facilisi. Suspendisse ante arcu, convallis non urna in, molestie fermentum augue. Integer volutpat diam arcu, sit amet efficitur urna faucibus eu.</p>
        </article>
        <div class="col-sm-12 col-4">
            <img src="{{media url="wysiwyg/sample-pictures/flower3.jpg"}}" alt="" />
        </div>
    </div>
</section>
<section>
<h2>Messages</h2>
<ul class="messages" style="list-style-type: none;">
    <li class="notice-msg">
        <ul style="margin: 0; list-style-type: none;"><li><span>This is a notice message.</span></li></ul>
    </li>
    <li class="success-msg">
        <ul style="margin: 0; list-style-type: none;"><li><span>This is a success message.</span></li></ul>
    </li>
    <li class="error-msg">
        <ul style="margin: 0; list-style-type: none;"><li><span>This is an error message.</span></li></ul>
    </li>
</ul>
</section>