<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if ($this->getItemCount()): ?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul class="products-list" id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <div class="item-inner">
                <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(80); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" width="80" height="80"
                /></a>
                <div class="product-shop">
                    <ul class="add-to-links add-to-links-mini">
                        <?php if ($this->helper('wishlist')->isAllow()): ?>
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_item)): ?>
                            <li class="link-compare"><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                    <h3 class="product-name">
                        <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a>
                    </h3>
                    <?php echo Mage::helper('core')->currency($_item->getFinalPrice(), true, false); ?>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
