<?php
/**
 * @category    design
 * @package     rwd_default
 */
?>

<?php $_creditmemo = $this->getCreditmemo() ?>
<?php $_order      = $this->getOrder() ?>

<?php if ($_creditmemo && $_order): ?>

    <?php $_items      = $_order->getAllItems() ?>
    <?php $_itemCount  = count($_items) ?>
    <table class="items" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td class="items-box">
                <table cellpadding="0" cellspacing="0" border="0">
                    <thead>
                    <tr>
                        <th class="cell-name">
                            <?php if($_itemCount > 1): echo $this->__('Items in your order'); else: echo $this->__('Item in your order'); endif; ?>
                        </th>
                        <th class="cell-name">
                            <?php echo $this->__('Qty'); ?>
                        </th>
                        <th class="cell-name align-right">
                            <?php echo $this->__('Unit Price'); ?>
                        </th>
                        <th class="cell-name">
                            <?php echo $this->__('Price'); ?>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i=0; foreach ($_creditmemo->getAllItems() as $_item): ?>
                        <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>

    <table class="totals-wrapper" cellpadding="0" cellspacing="0" border="0">
        <tfoot>
        <tr>
            <td colspan="5">
                <?php echo $this->getChildHtml('creditmemo_totals');?>
            </td>
        </tr>
        </tfoot>
    </table>
<?php endif; ?>
