<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_StoreCredit
 */
?>
<?php /** @var $this Amasty_StoreCredit_Block_Customer_Send */ ?>
<?php
$formData = $this->getFormData();
?>
<h2><?php echo $this->__('Send credit to friend');?></h2>
<div>
	<form id="amstcred-send-balance-form" action="<?php echo $this->getUrl('amstcred/customer/sendBalance') ?>" method="post">
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">

		<div class="fieldset">

			<ul class="form-list">
				<li>
					<label for="amstcred_send_recipient_name" class="required"><em>*</em> <?php echo $this->__('Friend Name') ?> </label>
					<div class="input-box">
						<input type="text" class="required-entry input-text" id="amstcred_send_recipient_name" name="amstcred_send[recipient_name]" value="<?php echo $this->escapeHtml($formData->getRecipientName());?>" />
					</div>
				</li>

				<li>
					<label for="amstcred_send_recipient_email" class="required"><em>*</em> <?php echo $this->__('Email') ?> </label>
					<div class="input-box">
						<input type="text" class="validate-email required-entry input-text" id="amstcred_send_recipient_email" name="amstcred_send[recipient_email]" value="<?php echo $this->escapeHtml($formData->getRecipientEmail());?>" />
					</div>
				</li>

				<li>
					<label for="amstcred_send_amount" class="required"><em>*</em> <?php echo $this->__('Amount') ?> </label>
					<div class="input-box">
						<input type="text" class="required-entry input-text" id="amstcred_send_amount" name="amstcred_send[amount]" value="<?php echo $this->escapeHtml($formData->getAmount());?>" />
					</div>
				</li>

				<li>
					<label for="amstcred_send_message"><?php echo $this->__('Message') ?> </label>
					<div class="input-box">
						<textarea class="input-text" id="amstcred_send_message" name="amstcred_send[message]"><?php echo $this->escapeHtml($formData->getMessage());?></textarea>
					</div>
				</li>
			</ul>


		</div>
		<div class="buttons-set form-buttons btn-only">
			<button class="button" onclick="AmStoreCreditSendBalanceForm.submit()" type="button" value="<?php echo $this->__('Submit') ?>"><span><span><?php echo $this->__('Submit') ?></span></span></button>
		</div>
	</form>

	<script type="text/javascript">
		//<![CDATA[
		var AmStoreCreditSendBalanceForm = new VarienForm('amstcred-send-balance-form');
		//]]>
	</script>
</div>

<br>