<?php
/**
 * This file is part of a Blugento Localizer e.V. module.
 *
 * @category  Blugento
 * @package   Blugento Localizer
 */
?>
<?php
/**
 * @var $this Blugento_Localizer_Block_Imprint_Content
 */
?>
<?php if (strlen(trim($this->getFinancialOffice()))): ?>
    <?php echo $this->__('Financial office') ?>: <?php echo $this->getFinancialOffice() ?><br />
<?php endif; ?>
<?php if (strlen(trim($this->getTaxNumber()))): ?>
    <?php echo $this->__('Tax number') ?>: <?php echo $this->getTaxNumber() ?><br />
<?php endif; ?>
<?php if (strlen(trim($this->getVatId()))): ?>
    <?php echo $this->__('VAT-ID') ?>: <?php echo $this->getVatId() ?><br />
<?php endif; ?>
