<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_StoreCredit
 */
?>
<?php /** @var $this Amasty_StoreCredit_Block_Checkout_Cart_Total */ ?>
<tr>
	<td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
		<?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
			<?php $_title = $this->__('Remove'); ?>
			<?php $_url = Mage::getUrl('amstcred/customer/removeCart', array('place'=>  Mage::app()->getRequest()->getRequestedControllerName())); ?>
			<a href="<?php echo $_url; ?>" title="<?php echo $_title; ?>" class="btn-remove btn-remove-amstcred"><img src="<?php echo $this->getSkinUrl('images/btn_remove.gif') ?>" alt="<?php echo $this->__('Remove')?>" /></a>
			<?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
			<?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
	</td>
	<td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
		<?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
			<?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
			<?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
	</td>
</tr>
