<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<?php $_newLogInLayout = (int) ($this->getLayout()->getBlock('root')->getMyAccountLoginNewLayout() ?: 1); ?>
<?php if ($_newLogInLayout == 1) : ?>
	<div class="page-title">
		<h1><?php echo $this->__('Login or Create an Account') ?></h1>
	</div>
	<div class="account-login">
	    <?php echo $this->getMessagesBlock()->toHtml() ?>
	    <?php /* Extensions placeholder */ ?>
	    <?php echo $this->getChildHtml('customer.form.login.extra')?>
		<?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin')) : ?>
			<?php echo $this->getLayout()->createBlock("fblogin/fblogin")->setTemplate("fblogin/fblogin.phtml")->toHtml(); ?>
		<?php endif; ?>
		<?php if (Mage::helper('core')->isModuleEnabled('Plumrocket_SocialLogin')) :?>
			<?php if (Mage::helper('pslogin')->modulePositionEnabled('register') && Mage::helper('pslogin')->hasButtons()) : ?>
				<?php echo $this->getChildHtml('pslogin_buttons'); ?>
			<?php endif; ?>
		<?php endif; ?>
		<?php if (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect') && Mage::helper('inchoo_googleconnect')->isEnabled()) : ?>
			<?php echo $this->getLayout()->createBlock("inchoo_googleconnect/button")->setTemplate("inchoo/googleconnect/button.phtml")->toHtml(); ?>
		<?php endif; ?>
		<strong class="title-info"><?php echo $this->__('---------------- sau ----------------'); ?></strong>
	    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
	        <?php echo $this->getBlockHtml('formkey'); ?>
	        <div class="registered-users">
	            <div class="content fieldset">
		            <ul class="form-list form-list--horizontal">
	                    <li>
	                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
	                        </div>
	                    </li>
	                    <li>
	                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
	                        <div class="input-box">
	                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
	                            <?php echo $this->getChildHtml('showpassword'); ?>
	                        </div>
	                    </li>
	                    <?php echo $this->getChildHtml('form.additional.info'); ?>
	                </ul>
	                <div class="buttons-set">
	                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
	                    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>"name="send" id="g-recaptcha-login" class="g-recaptcha-login button disabled" data-badge="bottomleft" data-size="invisible"><span><span><?php echo $this->__('Login') ?></span></span></button>
	                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	                </div>
	            </div>
	        </div>
	        <div class="new-users">
	            <div class="content fieldset">
	                <h2><?php echo $this->__('New Customers') ?></h2>
	                <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
	                <div class="buttons-set">
	                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
	                </div>
	            </div>
	        </div>
	    </form>
	    <script>
	        //<![CDATA[
	        var dataForm = new VarienForm('login-form', true);
	        //]]>
	    </script>

	    <script type="text/javascript">
	        //<![CDATA[
	        var dataForm = new VarienForm('form-validate', true);
	        <?php if($this->getShowAddressFields()): ?>
	        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
	        <?php endif; ?>
	        //]]>
	    </script>
	</div>
<?php elseif ($_newLogInLayout == 2) : ?>
	<div class="page-title">
		<h1><?php echo $this->__('Login or Create an Account') ?></h1>
	</div>
	<div class="account-login">
	    <?php echo $this->getMessagesBlock()->toHtml() ?>
	    <?php /* Extensions placeholder */ ?>
	    <?php echo $this->getChildHtml('customer.form.login.extra')?>
		<?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin')) : ?>
			<?php echo $this->getLayout()->createBlock("fblogin/fblogin")->setTemplate("fblogin/fblogin.phtml")->toHtml(); ?>
		<?php endif; ?>
		<?php if (Mage::helper('core')->isModuleEnabled('Plumrocket_SocialLogin')) :?>
			<?php if (Mage::helper('pslogin')->modulePositionEnabled('register') && Mage::helper('pslogin')->hasButtons()) : ?>
				<?php echo $this->getChildHtml('pslogin_buttons'); ?>
			<?php endif; ?>
		<?php endif; ?>
		<?php if (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect') && Mage::helper('inchoo_googleconnect')->isEnabled()) : ?>
			<?php echo $this->getLayout()->createBlock("inchoo_googleconnect/button")->setTemplate("inchoo/googleconnect/button.phtml")->toHtml(); ?>
		<?php endif; ?>
		<strong class="title-info"><?php echo $this->__('---------------- sau ----------------'); ?></strong>
	    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
	        <?php echo $this->getBlockHtml('formkey'); ?>
	        <div class="registered-users">
	            <div class="content fieldset">
	                <h2><?php echo $this->__('Registered Customers') ?></h2>
	                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
	                <ul class="form-list form-list--inline">
	                    <li>
	                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
	                        <div class="input-box">
	                            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" />
	                        </div>
	                    </li>
	                    <li>
	                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
	                        <div class="input-box">
	                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>" />
	                            <?php echo $this->getChildHtml('showpassword'); ?>
	                        </div>
	                    </li>
	                    <?php echo $this->getChildHtml('form.additional.info'); ?>
	                </ul>
	                <div class="buttons-set">
	                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
	                    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
	                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	                </div>
	            </div>
	        </div>
	        <div class="new-users">
	            <div class="content fieldset">
	                <h2><?php echo $this->__('New Customers') ?></h2>
	                <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
	                <div class="buttons-set">
	                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
	                </div>
	            </div>
	        </div>
	    </form>
	    <script>
	        //<![CDATA[
	        var dataForm = new VarienForm('login-form', true);
	        //]]>
	    </script>

	    <script type="text/javascript">
	        //<![CDATA[
	        var dataForm = new VarienForm('form-validate', true);
	        <?php if($this->getShowAddressFields()): ?>
	        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
	        <?php endif; ?>
	        //]]>
	    </script>
	</div>
<?php endif; ?>