<?php
/**
 * MindMagnet
 *
 * @category    MindMagnet
 * @package     MindMagnet_PrimeCheckout
 * @author      Daniel Gheoltan <daniel.gheoltan@mindmagnetsoftware.com>
 * @copyright   Copyright (c) 2011 Mind Magnet Software (http://www.mindmagnetsoftware.com)
 *
 */
?>
<h4><?php echo $this->__('Shipping Methods') ?>:</h4>

<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
    <script>
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/prime/saveShippingMethod') ?>");
    //]]>
    </script>
    <?php echo $this->getBlockHtml('formkey') ?>
</form>

<div id="onepage-checkout-shipping-method-additional-load">
    <?php echo $this->getChildHtml('additional') ?>
</div>

<div class="buttons-set" id="shipping-buttons-container">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="button" class="button" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span id="shipping-please-wait" class="please-wait" style="display: none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>
