<div class="box-head">
    <h2><?php echo $this->__('Address Book') ?></h2>
    <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
</div>
<div class="box">
    <div class="box-content">
        <div class="col2-set">
            <div class="col-1">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Billing Address') ?></h3>
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </div>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                </address>
            </div>
            <div class="col-2">
                <div class="box-title">
                    <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </div>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                </address>
            </div>
        </div>
    </div>
</div>
