<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>

<?php
$_cartViewProceedToCheckout = (int) ($this->getLayout()->getBlock('root')->getCartViewProceedToCheckout() ?: 2);
?>

<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="data-table cart-table">
            <colgroup>
                <col />
                <col />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col />
                <?php endif; ?>
            </colgroup>
            <tfoot>
            <tr>
                <td colspan="50" class="a-right">
                    <?php if ($this->getContinueShoppingUrl()): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" class="button btn-continue" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                    <?php endif; ?>

                    <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update Shopping Cart')); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>

                    <!--[if lt IE 8]>
                    <input type="hidden" id="update_cart_action_container" />
                    <script>
                        //<![CDATA[
                            Event.observe(window, 'load', function()
                            {
                                // Internet Explorer (lt 8) does not support value attribute in button elements
                                $emptyCartButton = $('empty_cart_button');
                                $cartActionContainer = $('update_cart_action_container');
                                if ($emptyCartButton && $cartActionContainer) {
                                    Event.observe($emptyCartButton, 'click', function()
                                    {
                                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                                        $cartActionContainer.setValue('empty_cart');
                                    });
                                }

                            });
                        //]]>
                    </script>
                    <![endif]-->
                </td>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach ($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </form>
    <div class="cart-collaterals" id="cart-collaterals-section" data-cart-collaterals-fixed="<?php echo $_cartViewProceedToCheckout; ?>">
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout.cart.extra') ?>
	    <?php echo $this->getChildHtml('facebookdiscount.like'); ?>
        <?php echo $this->getChildHtml('coupon') ?>
        <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
        <div class="cart-totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
                <ul class="checkout-types">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <li><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('delivery_day_cart') ?>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>

<?php if (Mage::helper('core')->isModuleEnabled('Retargeting_Tracker')): ?>
    <script>
        var _ra = _ra || {};
        _ra.setCartUrlInfo = {
            "url": "<?php echo Mage::getBaseUrl() . 'checkout/cart'; ?>"
        };

        if (_ra.ready !== undefined) {
            _ra.setCartUrl(_ra.setCartUrlInfo.url);
        }
    </script>
<?php endif; ?>
