<?php
$helper = Mage::helper('blugento_gdpruserdata');
?>

<form action="<?php echo $this->getExportFormAction() ?>" id="gdpr-export-form" method="POST">
    <div class="fieldset">
        <h2 class="legend"><?php echo $helper->__('Export My Data') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="email-contact" class="required"><em>*</em><?php echo $helper->__('Email Address') ?></label>
                    <input name="email_contact" id="email-contact" title="<?php echo $helper->__('Email Address') ?>" class="input-text required-entry validate-email" type="email" value="<?php echo $this->getCustomerEmail() ?>">
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* <?php echo $helper->__('Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;">

        <button type="submit" title="<?php echo $helper->__('Submit Request') ?>" name="send" id="g-recaptcha-export" class="g-recaptcha-export button disabled" data-badge="bottomleft" data-size="invisible" ><span><span><?php echo $helper->__('Submit Request') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    var contactForm = new VarienForm('gdpr-export-form', false);
</script>

<?php if (Mage::helper('core')->isModuleEnabled('Magecomp_Recaptcha')): ?>
    <script>
        function onSubmitExport(token) {
            setTimeout(function(){
                jQuery('.g-recaptcha-export').attr('data-token', token);

                return new Promise(function (resolve, reject) {
                    var dataForm = new VarienForm('gdpr-export-form');
                    var tokenHash = jQuery('.g-recaptcha-export').attr('data-token');

                    if (tokenHash && tokenHash.length > 100) {
                        if (dataForm.validator && dataForm.validator.validate()){
                            jQuery('#gdpr-export-form').attr('action', '<?php echo $this->getAction() ?>');
                            document.getElementById("gdpr-export-form").submit();
                        }
                    }
                });
            }, 500);
        }

        // Check if captcha container have loaded class, if not than captcha will be loaded
        function loadCaptchaExport() {
            setTimeout(function(){
                // Fix for google recaptcha from 18 June
				if ("NodeList" in window) {
					if (!NodeList.prototype.each && NodeList.prototype.forEach) {
						NodeList.prototype.each = NodeList.prototype.forEach;
					}
				}

                if (!jQuery('.captcha_container_export').length) {
                    jQuery('#g-recaptcha-export').addClass('captcha_container_export');
                    var captchaContainer = null;
                    var loadCaptchaExportFunction = function() {
                        captchaContainer = grecaptcha.render('g-recaptcha-export', {
                            'sitekey': '<?php echo $this->helper('recaptcha')->getKey(); ?>',
                            'callback': onSubmitExport
                        });
                    };

                    loadCaptchaExportFunction();
                }
            }, 300);
        };

        // Once user insert a value, loadCaptchaContent will be called
        jQuery('#export-form input').each(function(e) {
            jQuery(this).on('input', function(e) {
                loadCaptchaExport();
            });
        });

        // Once inputs are autofilled show captcha
		if(jQuery('#email-contact:-webkit-autofill')){
			if (!jQuery('.captcha_container_login').length) {
				loadCaptchaExport();
			}
		}

        jQuery('.g-recaptcha-export').on('click', function(e) {
            onSubmitExport();
        });
    </script>
    <script src="https://www.google.com/recaptcha/api.js?onload=loadCaptchaExportFunction&render=explicit" async defer></script>
<?php endif; ?>

