<?php
$seoHelper = $this->helper('blugento_seoenhancements/siteLogo');

if ($seoLogo = $seoHelper->getNewSiteLogo()) {
	$logoImage = $seoLogo;
} else {
	// Get logo image from variable-image.xml
	$logoImage = Mage::helper('blugento_theme')->getVariable('page_brand_logo', 'image', 'var_page_brand_logo.png');
    $extension = pathinfo($logoImage, PATHINFO_EXTENSION);

    if ($extension == 'svg') {
        $logoImage = $this->getSkinUrl('blugento/images/' . $logoImage);
    } else {
        $logoImage = $this->getSkinUrl('images/' . $logoImage);
    }
}

$blockCms = Mage::getStoreConfig('ajaxlogin/options/add_cms_block');
?>

<div class="ajax-login-modal dock">
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <div id="ajaxlogin-mask-enabled"></div>
        <div id="ajaxlogin-login-window" class="ajaxlogin-window">
            <?php if (Mage::getStoreConfig('ajaxlogin/options/enable_logo')): ?>
                <div class="logo-pop-up">
                    <img src="<?php echo $logoImage ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </div>
            <?php endif; ?>
	
	        <?php if (Mage::getStoreConfig('ajaxlogin/options/button_placement') === 'top'): ?>
		        <div class="top-pop-up-buttons">
			        <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="login-btn"><?php echo $this->__('Login') ?></a>
			        <?php if (Mage::getStoreConfig('ajaxlogin/options/button_action') === '1'): ?>
			            <a class="pop-up-register" title="<?php echo $this->__('Register') ?>" name="noaccount" id="noaccount-ajax-login" rel="nofollow"><?php echo $this->__('Create an Account') ?></a>
			        <?php elseif (Mage::getStoreConfig('ajaxlogin/options/button_action') === '2'): ?>
				        <a class="pop-up-cms-block" name="cmsblock" id="cmsblock"><?php echo $this->__('Send inquiry') ?></a>
			        <?php  endif; ?>
		        </div>
	        <?php endif; ?>
	        
            <?php if (!Mage::getStoreConfig('gdpr_cookies/general/enabled') || Mage::getSingleton('core/cookie')->get('marketing') == 'yes') : ?>
                <div class="social_account">
                    <?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin') || Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect')) : ?>
                        <h2><?php echo $this->__('Use Account') ?></h2>
                    <?php endif; ?>
                    <div class="cf">
                        <?php if (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect') && Mage::helper('inchoo_googleconnect')->isEnabled()) : ?>
                            <?php echo $this->getLayout()->createBlock("inchoo_googleconnect/button")->setTemplate("inchoo/googleconnect/button.phtml")->toHtml(); ?>
                        <?php endif; ?>
                        <?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin')) : ?>
                            <?php echo $this->getLayout()->createBlock("fblogin/fblogin")->setTemplate("fblogin/fblogin.phtml")->toHtml(); ?>
                        <?php endif; ?>
                    </div>
                    <?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin') || Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect')) : ?>
                        <span class="or-divider"><span><?php echo $this->__('or') ?></span></span>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <form action="<?php echo $this->getUrl('ajaxlogin/index/login', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-login-form">
	            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <h2><?php echo $this->__('Login with your email') ?></h2>
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                <div class="content">
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                </div>
                <div class="buttons-set">
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left forgot-btn"><?php echo $this->__('Forgot Your Password?') ?></a>
	                <button type="submit" title="<?php echo $this->__('Login') ?>" name="send" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
	                <?php if (Mage::getStoreConfig('ajaxlogin/options/button_placement') === 'default'): ?>
	                    <p>
	                        <span><?php echo $this->__('You don\'t have an account?') ?></span>
	                        <a class="pop-up-register" title="<?php echo $this->__('Register') ?>" name="noaccount" id="noaccount" rel="nofollow"><?php echo $this->__('Create an Account') ?></a>
	                    </p>
	                <?php endif; ?>
                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var ajaxLoginForm = new VarienForm('ajaxlogin-login-form', true);
                //]]>
            </script>


        </div>
    <?php endif; ?>

    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <div id="ajaxlogin-forgot-window">
            <?php if (Mage::getStoreConfig('ajaxlogin/options/enable_logo')): ?>
                <div class="logo-pop-up">
                    <img src="<?php echo $logoImage ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </div>
            <?php endif; ?>
            <form action="<?php echo $this->getUrl('ajaxlogin/index/forgotpassword', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-forgot-password-form">
                <h2><?php echo $this->__('Forgot Your Password?') ?></h2>    
                <div class="content">
                    <?php
                    $customerHelper = Mage::helper('customer');
                    if (method_exists($customerHelper, 'generateResetPasswordLinkToken')) : ?>
                        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
                    <?php else: ?>
                        <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
                    <?php endif; ?>
                    <ul class="form-list">
                        <li>
                            <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" name="email" id="email_address_recover" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                </div>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="login-btn"><?php echo $this->__('Back to Login') ?></a></p>
                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var ajaxForgotForm = new VarienForm('ajaxlogin-forgot-password-form', true);
                //]]>
            </script>
        </div>
    <?php endif; ?>

    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn() && Mage::getStoreConfig('ajaxlogin/options/button_action') === '1'): ?>
        <div id="ajaxlogin-create-window">
            <?php if (Mage::getStoreConfig('ajaxlogin/options/enable_logo')): ?>
                <div class="logo-pop-up">
                    <img src="<?php echo $logoImage ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </div>
            <?php endif; ?>
	        <?php if (Mage::getStoreConfig('ajaxlogin/options/button_placement') === 'top'): ?>
		        <div class="top-pop-up-buttons">
			        <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="login-btn"><?php echo $this->__('Login') ?></a>
			        <a class="pop-up-register" title="<?php echo $this->__('Register') ?>" name="noaccount" id="noaccount" rel="nofollow"><?php echo $this->__('Create an Account') ?></a>
		        </div>
	        <?php endif; ?>
            <form action="<?php if (Mage::helper('core')->isModuleEnabled('Magecomp_Recaptcha') && $this->helper('recaptcha')->showOnRegister()): ?><?php else: ?><?php echo $this->getUrl('ajaxlogin/index/create', array('_secure'=>true)) ?><?php endif; ?>" method="post" id="ajaxlogin-create-form">
                <h2><?php echo $this->__('Create account') ?></h2>
                <?php echo $this->getChildHtml(); ?>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var ajaxCreateForm = new VarienForm('ajaxlogin-create-form', true);
                //]]>
            </script>
        </div>
    <?php endif; ?>

    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <div id="ajaxlogin-logout-window">
            <?php if (Mage::getStoreConfig('ajaxlogin/options/enable_logo')): ?>
                <div class="logo-pop-up">
                    <img src="<?php echo $logoImage ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                </div>
            <?php endif; ?>
            <form action="<?php echo $this->getUrl('ajaxlogin/index/logout', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-logout-form">
                <h2><?php echo $this->__('Logout from your account') ?></h2>    
                <div class="content">
                <p><?php echo $this->__('Are you sure you want to log out?') ?></p>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Logout') ?></span></span></button>
                </div>
            </form>
            <script type="text/javascript">
                //<![CDATA[
                var ajaxLogoutForm = new VarienForm('ajaxlogin-logout-form', true);
                //]]>
            </script>
        </div>
    <?php endif; ?>
	
	<?php if (!Mage::getSingleton('customer/session')->isLoggedIn() && Mage::getStoreConfig('ajaxlogin/options/button_action') === '2'): ?>
		<div id="ajaxlogin-cms-block-window">
			<?php if (Mage::getStoreConfig('ajaxlogin/options/enable_logo')): ?>
				<div class="logo-pop-up">
                    <img src="<?php echo $logoImage ?>" alt="<?php echo $this->getLogoAlt() ?>" />
				</div>
			<?php endif; ?>
			<?php if (Mage::getStoreConfig('ajaxlogin/options/button_placement') === 'top'): ?>
				<div class="top-pop-up-buttons">
					<a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="login-btn"><?php echo $this->__('Login') ?></a>
					<a class="pop-up-cms-block" name="cmsblock" id="cmsblock"><?php echo $this->__('Send inquiry') ?></a>
				</div>
			<?php endif; ?>
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($blockCms)->toHtml(); ?>
		</div>
	<?php endif; ?>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function() {
        var triggers = {
            login: {
                el    : $$('.login-btn'),
                event : 'click',
                window: $('ajaxlogin-login-window')
            },
            create: {
                el    : $$('#noaccount'),
                event : 'click',
                window: $('ajaxlogin-create-window')
            },
            forgot: {
                el    : $$('.forgot-btn'),
                event : 'click',
                window: $('ajaxlogin-forgot-window')
            },
            logout: {
                el    : $$('.logout-btn'),
                event : 'click',
                window: $('ajaxlogin-logout-window')
            },
	        cmsblock: {
		        el    : $$('#cmsblock'),
		        event : 'click',
		        window: $('ajaxlogin-cms-block-window')
	        }
        };
        ajaxLoginWindow = new AjaxLogin({
            triggers: triggers
        });
    });
</script>
