<?php
$storeId = Mage::app()->getStore()->getStoreId();
?>
<?php if (!Mage::getStoreConfig('gdpr_cookies/general/enabled') || Mage::getSingleton('core/cookie')->get('marketing') == 'yes') : ?>
    <?php echo $this->getScriptCode('cart', $storeId); ?>
<?php endif; ?>

<?php echo $this->getScriptCode('cart_necessary', $storeId); ?>

<?php if (!Mage::getStoreConfig('gdpr_cookies/general/enabled') || Mage::getSingleton('core/cookie')->get('statistics') == 'yes') : ?>
    <?php echo $this->getScriptCode('cart_analytics', $storeId); ?>
<?php endif; ?>

