<?php
/**
 * MindMagnet
 *
 * @category    MindMagnet
 * @package     MindMagnet_PrimeCheckout
 * @author      Daniel Gheoltan <daniel.gheoltan@mindmagnetsoftware.com>
 * @copyright   Copyright (c) 2011 Mind Magnet Software (http://www.mindmagnetsoftware.com)
 *
 */

/* @var MindMagnet_PrimeCheckout_Block_Prime_Login $this */
?>
<?php $_quoteCheckoutMethod = $this->getQuote()->getCheckoutMethod(); ?>

<?php if (!$this->isCustomerLoggedIn()): ?>

<div class="col2-set">
    <?php echo $this->getChildHtml('login_before') ?>
    <div class="col-1">
        <h3><?php echo $this->__('Checkout Method') ?></h3>
        <ul class="form-list">
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
            <li class="control">
                <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if ($_quoteCheckoutMethod == Mage_Checkout_Model_Type_Onepage::METHOD_GUEST || ($this->getQuote()->isAllowedGuestCheckout() && empty($_quoteCheckoutMethod))): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
            </li>
            <?php endif; ?>
            <li class="control">
                <input type="radio" name="checkout_method" id="login:register" value="register"<?php if ($_quoteCheckoutMethod == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || (!$this->getQuote()->isAllowedGuestCheckout() && empty($_quoteCheckoutMethod))): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
            </li>
        </ul>
        <ul class="form-list">
            <li class="control">
                <input type="radio" name="checkout_method" id="login:login_in" value="login_in"<?php if ($_quoteCheckoutMethod == Mage_Checkout_Model_Type_Onepage::METHOD_CUSTOMER || $_quoteCheckoutMethod == Mage_Sales_Model_Quote::CHECKOUT_METHOD_LOGIN_IN): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:login_in"><?php echo $this->__('Login') ?></label>
            </li>
        </ul>
        <?php echo $this->getChildHtml('checkout_methods_after') ?>
    </div>
    <div class="col-2">
        <h3>&nbsp;</h3>
        <div id="co-login-error-msg">
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        </div>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <?php echo $this->getBlockHtml('formkey') ?>
            <fieldset>
                <ul class="form-list">
                    <li>
                        <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-password" id="login-password" name="login[password]" />
                        </div>
                    </li>
                    <li>
                        <label for="login-confirm-password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-cpassword" id="login-confirm-password" name="login[confirm_password]" />
                        </div>
                    </li>
                    <?php echo Mage::helper('primecheckout')->getPersistentRememberMe() ?>
                </ul>
                <?php echo Mage::helper('primecheckout')->getPersistentRememberMeTooltip() ?>
            </fieldset>
            <?php echo $this->getBlockHtml('formkey') ?>
        </form>
        <div class="buttons-set" id="login-buttons-container">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
            <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="account.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span class="please-wait" id="login-please-wait" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
            </span>
        </div>
    </div>
</div>
<script>
//<![CDATA[
    var account = new Account('login-form', '<?php echo $this->getPostAction() ?>', '<?php echo $this->getUrl('checkout/prime/saveMethod') ?>', <?php echo Mage::helper('core')->jsonEncode((bool)$this->isCustomerLoggedIn()) ?>,  '<?php echo $this->getForgotpasswordUrl() ?>');

    var loginForm = new VarienForm('login-form', true);

    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    $('login-confirm-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            account.save();
        }
    }
    jQuery('.form-list').click(function() {
        jQuery('#co-login-error-msg').hide();
    });
//]]>
</script>

<?php else: ?>

<div class="col2-set">
    <?php echo $this->getChildHtml('login_before') ?>
    <div class="col-1">
        <h3><?php echo $this->__('Checkout as loged in customer') ?></h3>
        <p><?php echo $this->__('You are curentlly loged in as: <strong>%s %s</strong>', $this->getCustomer()->getFirstname(), $this->getCustomer()->getLastname()) ?></p>
        <input type="hidden" name="checkout_method" id="login:login_in" value="login_in" checked="checked" />
        <div class="buttons-set" id="login-buttons-container">
            <a href="<?php echo $this->getUrl('customer/account/logout') ?>" class="f-left"><?php echo $this->__('Log Out') ?></a>
            <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span class="please-wait" id="login-please-wait" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
            </span>
        </div>
    </div>
    <div class="col-2">
    </div>
</div>

<?php endif; ?>
