<?php
/**
 * MindMagnet
 *
 * @category    MindMagnet
 * @package     MindMagnet_PrimeCheckout
 * @author      Daniel Gheoltan <daniel.gheoltan@mindmagnetsoftware.com>
 * @copyright   Copyright (c) 2011 Mind Magnet Software (http://www.mindmagnetsoftware.com)
 *
 */
?>
<?php
$_showIdOnFieldset = (version_compare(Mage::getVersion(), '1.8.0.0', '>=') && Mage::getEdition() == 'Community')
                      || (version_compare(Mage::getVersion(), '1.13.0.0', '>=') && Mage::getEdition() == 'Enterprise');
?>

<?php echo $this->getChildHtml('billing') ?>

<h4><?php echo $this->__('Payment Method') ?>:</h4>
<script type="text/javascript">
//<![CDATA[
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/prime/savePayment') ?>');
//]]>
</script>
<form action="" id="co-payment-form">
    <dl class="sp-methods"<?php if ($_showIdOnFieldset) echo ' id="checkout-payment-method-load"' ?>>
        <?php echo $this->getChildHtml('methods') ?>
    </dl>
    <?php echo $this->getBlockHtml('formkey') ?>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display: none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>

<div class="buttons-set" id="payment-buttons-container">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="button" class="button" onclick="payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span class="please-wait" id="payment-please-wait" style="display: none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>

<script>
//<![CDATA[
    function toggleToolTip(event) {
        if ($('payment-tool-tip')) {
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event) - 560) + 'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if ($('payment-tool-tip-close')) {
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
