<?php
$_cartViewProceedToCheckoutMobile = (int) ($this->getLayout()->getBlock('root')->getCartViewProceedToCheckoutMobile() ?: 1);
?>
<?php if ($this->isPossibleOnepageCheckout()) : ?>
	<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Proceed to Checkout')) ?>" id="button_proceed_to_checkout" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
		<span>
			<span><?php echo $this->__('Proceed to Checkout') ?></span>
		</span>
	</button>
	<?php if ($_cartViewProceedToCheckoutMobile == 1) : ?>
		<span type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" id="btn-proceed-checkout-fixed" class="button no-display btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>">
			<span>
				<span><?php echo $this->__('Proceed to Checkout') ?></span>
			</span>
		</span>
	<?php endif; ?>
<?php endif?>
