<?php
	$_checkoutNewLayOut = (int) ($this->getLayout()->getBlock('root')->getCheckoutViewNewLayout() ?: 2);
	$_checkoutAsideItems = (int) ($this->getLayout()->getBlock('root')->getCheckoutAsideItems() ?: 2);
?>
<?php if ($_checkoutAsideItems == 1) : ?>
	<div class="page-title">
		<h1><?php echo $this->__('Checkout') ?></h1>
	</div>
<?php endif; ?>
<?php if ($_checkoutNewLayOut == 2) : ?>
	<div class="block block-progress opc-block-progress">
		<div class="block-title">
			<strong><span><?php echo $this->__('Your Checkout Progress') ?></span></strong>
		</div>
		<div class="block-content">
			<dl>
				<?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
					<div id="billing-progress-opcheckout">
						<?php echo $this->getChildHtml('billing.progress') ?>
					</div>
				<?php endif; ?>
				
				<?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
					<div id="shipping-progress-opcheckout">
						<?php echo $this->getChildHtml('shipping.progress') ?>
					</div>
				<?php endif; ?>
				
				<?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
					<div id="shipping_method-progress-opcheckout">
						<?php echo $this->getChildHtml('shippingmethod.progress') ?>
					</div>
				<?php endif; ?>
				
				<?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
					<div id="payment-progress-opcheckout">
						<?php echo $this->getChildHtml('payment.progress') ?>
					</div>
				<?php endif; ?>
			</dl>
		</div>
	</div>
<?php elseif ($_checkoutNewLayOut == 1) : ?>
	<div class="block block-progress opc-block-progress">
		<div class="block-content">
			<dl>
				<?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
					<div id="billing-progress-opcheckout">
						<?php echo $this->getChildHtml('billing.progress') ?>
					</div>
				<?php endif; ?>

				<?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
					<div id="shipping-progress-opcheckout">
						<?php echo $this->getChildHtml('shipping.progress') ?>
					</div>
				<?php endif; ?>
				
				<?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
					<div id="shipping_method-progress-opcheckout">
						<?php echo $this->getChildHtml('shippingmethod.progress') ?>
					</div>
				<?php endif; ?>
				
				<?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
					<div id="payment-progress-opcheckout">
						<?php echo $this->getChildHtml('payment.progress') ?>
					</div>
				<?php endif; ?>
			</dl>
		</div>
	</div>
<?php endif; ?>
