<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<?php $_checkoutNewLayOut = (int) ($this->getLayout()->getBlock('root')->getCheckoutViewNewLayout() ?: 2); ?>
<?php if ($_checkoutNewLayOut == 2) : ?>
	<div class="col2-set">
		<?php echo $this->getChildHtml('login_before')?>
		<div class="col-1">
			<h3><?php if ($this->getQuote()->isAllowedGuestCheckout()): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
			<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
				<h4><?php echo $this->__('Register with us for future convenience:') ?></h4>
			<?php else: ?>
				<p><strong><?php echo $this->__('Register and save time!') ?></strong></p>
				<p><?php echo $this->__('Register with us for future convenience:') ?></p>
				<ul>
					<li><?php echo $this->__('Fast and easy check out') ?></li>
					<li><?php echo $this->__('Easy access to your order history and status') ?></li>
				</ul>
			<?php endif; ?>
			<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
				<ul class="form-list">
					<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
						<li class="control">
							<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if ($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
						</li>
					<?php endif; ?>
					<li class="control">
						<input type="radio" name="checkout_method" id="login:register" value="register"<?php if ($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
					</li>
				</ul>
			<?php else: ?>
				<input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
			<?php endif; ?>
			
			<div class="buttons-set">
				
				<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
					<button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
				<?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
					<button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
				<?php else: ?>
					<form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
						<button id="onepage-guest-register-button" type="submit" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
					</form>
				<?php endif; ?>
			</div>
		</div>
		<div class="col-2">
			<h3><?php echo $this->__('Login') ?></h3>
			<?php echo $this->getMessagesBlock()->toHtml() ?>
			<form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
				<fieldset>
					<?php echo $this->getBlockHtml('formkey'); ?>
					<h4><?php echo $this->__('Already registered?') ?></h4>
					<p><?php echo $this->__('Please log in below:') ?></p>
					<ul class="form-list">
						<li class="field">
							<label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
							<div class="input-box">
								<input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
							</div>
						</li>
						<li class="field">
							<label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
							<div class="input-box">
								<input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
								<?php echo $this->getChildHtml('showpassword'); ?>
							</div>
						</li>
						<?php echo $this->getChildHtml('form.additional.info'); ?>
						<?php echo $this->getChildHtml('persistent.remember.me'); ?>
					</ul>
					<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
					<input name="context" type="hidden" value="checkout" />
				</fieldset>
				<div class="buttons-set">
					<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
					<button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
					<?php if ( Mage::helper('core')->isModuleEnabled('Magestore_Fblogin')) : ?>
						<?php echo $this->getLayout()->createBlock("fblogin/fblogin")->setTemplate("fblogin/bt_fblogin.phtml")->toHtml(); ?>
					<?php endif; ?>
					<?php if (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect') && Mage::helper('inchoo_googleconnect')->isEnabled()) : ?>
						<?php echo $this->getLayout()->createBlock("inchoo_googleconnect/button")->setTemplate("inchoo/googleconnect/button.phtml")->toHtml(); ?>
					<?php endif; ?>
				
				</div>
			</form>
		</div>
	</div>
	<script>
			//<![CDATA[
			var loginForm = new VarienForm('login-form', true);
			$('login-email').observe('keypress', bindLoginPost);
			$('login-password').observe('keypress', bindLoginPost);
			function bindLoginPost(evt){
				if (evt.keyCode == Event.KEY_RETURN) {
					loginForm.submit();
				}
			}
			function onepageLogin(button)
			{
				if (loginForm.validator && loginForm.validator.validate()){
					button.disabled = true;
					loginForm.submit();
				}
			}
			//]]>
	</script>
	<?php
	$registerParam = $this->getRequest()->getParam('register');
	if ($registerParam || $registerParam === ''):
		?>
		<script>
					//<![CDATA[
					document.observe("dom:loaded", function() {
						if ($('login:register')) {
							$('login:register').checked = true;
							checkout.setMethod();
						}
					})
					//]]>
		</script>
	<?php endif; ?>
<?php elseif ($_checkoutNewLayOut == 1) : ?>
	<div class="col2-set">
	    <?php echo $this->getChildHtml('login_before')?>
	    <div class="col-12">
	        <h3><?php if ($this->getQuote()->isAllowedGuestCheckout()): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
	        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
	            <p><?php //echo $this->__('Register with us for future convenience:') ?></p>
	        <?php else: ?>
	            <div class="register-info">
		            <p><strong><?php echo $this->__('Register and save time!') ?></strong></p>
		            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
		            <ul>
			            <li><?php echo $this->__('Fast and easy check out') ?></li>
			            <li><?php echo $this->__('Easy access to your order history and status') ?></li>
		            </ul>
	            </div>
	        <?php endif; ?>
	        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
	            <ul class="form-list">
		            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
			            <li class="control">
				            <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if ($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
			            </li>
		            <?php endif; ?>
		            <li class="control">
			            <input type="radio" name="checkout_method" id="login:register" value="register"<?php if ($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
		            </li>
		            <li class="control">
			            <input onclick="checkout.setMethod();" type="radio" name="checkout_method" id="login:login_in" value="login_in"<?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_CUSTOMER || $this->getQuote()->getCheckoutMethod() == Mage_Sales_Model_Quote::CHECKOUT_METHOD_LOGIN_IN): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:login_in"><?php echo $this->__('Login') ?></label>
		            </li>
	            </ul>
	        <?php else: ?>
	            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
	        <?php endif; ?>
		    
		    <div class="buttons-set">
			    <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
				    <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
			    <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
				    <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
			    <?php else: ?>
				    <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
					    <button id="onepage-guest-register-button" type="submit" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
				    </form>
			    <?php endif; ?>
		    </div>
	    </div>
	    <div class="col-12" id="showLogInForm">
	        <h3><?php echo $this->__('Login') ?></h3>
	        <?php echo $this->getMessagesBlock()->toHtml() ?>
	        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
		        <fieldset>
		            <?php echo $this->getBlockHtml('formkey'); ?>
		            <h4><?php echo $this->__('Already registered?') ?></h4>
		            <p><?php echo $this->__('Please log in below:') ?></p>
		            <ul class="form-list">
		                <li class="field">
		                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
		                    <div class="input-box">
		                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
		                    </div>
		                </li>
		                <li class="field">
		                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
		                    <div class="input-box">
		                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
		                        <?php echo $this->getChildHtml('showpassword'); ?>
		                    </div>
		                </li>
		                <?php echo $this->getChildHtml('form.additional.info'); ?>
		                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
		            </ul>
			        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
		            <input name="context" type="hidden" value="checkout" />
		        </fieldset>
		        <div class="buttons-set">
			        <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
			        <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
			        <?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin') || (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect')  && Mage::helper('inchoo_googleconnect')->isEnabled())) : ?>
				        <strong class="title-info"><?php echo $this->__('---------------- sau -----------------') ?></strong>
			        <?php endif; ?>
			        <?php if (Mage::helper('core')->isModuleEnabled('Magestore_Fblogin')) : ?>
				        <?php echo $this->getLayout()->createBlock("fblogin/fblogin")->setTemplate("fblogin/bt_fblogin.phtml")->toHtml(); ?>
			        <?php endif; ?>
			        <?php if (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect') && Mage::helper('inchoo_googleconnect')->isEnabled()) : ?>
				        <?php echo $this->getLayout()->createBlock("inchoo_googleconnect/button")->setTemplate("inchoo/googleconnect/button.phtml")->toHtml(); ?>
			        <?php endif; ?>
		        </div>
	        </form>
	    </div>
	</div>
	<script>
	//<![CDATA[
	    var loginForm = new VarienForm('login-form', true);
	    $('login-email').observe('keypress', bindLoginPost);
	    $('login-password').observe('keypress', bindLoginPost);
	    function bindLoginPost(evt){
	        if (evt.keyCode == Event.KEY_RETURN) {
	            loginForm.submit();
	        }
	    }
	    function onepageLogin(button)
	    {
	        if (loginForm.validator && loginForm.validator.validate()){
	            button.disabled = true;
	            loginForm.submit();
	        }
	    }
		$('showLogInForm').hide();
		var checkoutList = document.getElementById('checkoutSteps');
		$('login:guest').observe('click', function () {
			if ($('login:guest').checked) {
				$('showLogInForm').hide();
				if (checkoutList.dataset.orientation == 2) {
					var currentSection = document.getElementById('opc-login');
					var targetHeight = currentSection.getElementsByClassName('step')[0].offsetHeight;
					var titleHeight = currentSection.getElementsByClassName('step-title')[0].offsetHeight;
					var height = titleHeight + targetHeight;
					checkoutList.setAttribute('style', 'min-height: ' + height + 'px');
				}
			}
		});
		$('login:register').observe('click', function () {
			if ($('login:register').checked || $('login:register').type == 'hidden') {
				$('showLogInForm').hide();
				if (checkoutList.dataset.orientation == 2) {
					var currentSection = document.getElementById('opc-login');
					var targetHeight = currentSection.getElementsByClassName('step')[0].offsetHeight;
					var titleHeight = currentSection.getElementsByClassName('step-title')[0].offsetHeight;
					var height = titleHeight + targetHeight;
					checkoutList.setAttribute('style', 'min-height: ' + height + 'px');
				}
			}
		});
	//]]>
	</script>
	<?php
	    $registerParam = $this->getRequest()->getParam('register');
	    if ($registerParam || $registerParam === ''):
	?>
	    <script>
	    //<![CDATA[
	        document.observe("dom:loaded", function() {
	            if ($('login:register')) {
	                $('login:register').checked = true;
	                checkout.setMethod();
	            }
	        })
	    //]]>
	    </script>
	<?php endif; ?>
<?php endif; ?>
