<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */

 $_filterNofollow = Mage::getStoreConfig('blugento_seoenhancements/enhancements_group/add_nofollow_on_filters_link');
?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount() > 0): ?>
            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" <?php if ($_filterNofollow): ?>rel="nofollow"<?php endif; ?>><?php echo $_item->getLabel() ?></a>
        <?php else: ?>
            <?php echo $_item->getLabel() ?>
        <?php endif; ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
            <em>(<?php echo $_item->getCount() ?>)</em>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ol>
