<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.16
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
$layoutStylingView = Mage::getStoreConfig('blog/blog/layout_styling_view');
$post = $this->getPost();
?>
<div class="blog-wrap blog-<?php echo $layoutStylingView ?>">
    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="postWrapper">
        <div class="postTitle">
            <?php if ($postImage = $post->getFeaturedImage()): ?>
                <?php $postImage = $this->getPostImage($post->getFeaturedImage()); ?>
                <img src="<?php echo $postImage; ?>" alt="<?php echo $post->getTitle(); ?>" />
            <?php endif; ?>
            <h1><?php echo $post->getTitle(); ?></h1>
            <div><?php echo $post->getCreatedTime(); ?></div>
        </div>

        <div class="postContent std">
            <?php echo $post->getPostContent(); ?>
            <?php if ($layoutStylingView == 'layout-2'): ?>
                <div class="postDetails">
                    <?php $postCats = $post->getCats(); ?>
                    <?php if (!empty($postCats)): ?>
                        <strong>
                            <?php echo Mage::helper('blog')->__('Posted in'); ?>
                            <?php foreach ($postCats as $title => $url): ?>
                                <a href="<?php echo $url; ?>"><?php echo $title; ?></a>
                            <?php endforeach; ?>
                        </strong>
                    <?php else: ?>
                        <strong>
                            <?php echo Mage::helper('blog')->__('Posted'); ?>
                        </strong>
                    <?php endif; ?>
                    <strong>
                        <?php echo $this->__("By:"); ?>
                    </strong>
                    <div class="poster"><?php echo $post->getUser(); ?></div>
                </div>
            <?php endif; ?>
        </div>

        <div class="content-bottom-blog">
            <?php echo $this->getBookmarkHtml($post); ?>
            <div class="content-right-blog">
                <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
                <?php if ($layoutStylingView != 'layout-2'): ?>
                    <div class="postDetails">
                        <?php $postCats = $post->getCats(); ?>
                        <?php if (!empty($postCats)): ?>
                            <strong>
                                <?php echo Mage::helper('blog')->__('Posted in'); ?>
                                <?php foreach ($postCats as $title => $url): ?>
                                    <a href="<?php echo $url; ?>"><?php echo $title; ?></a>
                                <?php endforeach; ?>
                            </strong>
                        <?php else: ?>
                            <strong>
                                <?php echo Mage::helper('blog')->__('Posted'); ?>
                            </strong>
                        <?php endif; ?>
                        <strong>
                            <?php echo $this->__("By:"); ?>
                        </strong>
                        <div class="poster"><?php echo $post->getUser(); ?></div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <!-- Comment Section -->

    <?php if ($this->getCommentsEnabled()): ?>
        <div class="comments-form">
            <?php $comments = $this->getComment(); ?>
            <div class="postTitle"><a name="commentBox" ></a>
                <div><?php echo $this->__('Post Comments') ?></div>
            </div>

            <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
            <?php foreach ($comments as $comment) : ?>
                <div class="commentWrapper">
                    <div class="commentDetails"><h4 class="username"><?php echo $this->getClearComment($comment->getUser()); ?></h4> <?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                    <div class="commentContent"><?php echo nl2br($this->getClearComment($comment->getComment())); ?></div>
                </div>
            <?php endforeach; ?>

            <?php if ($post->getComments()): ?>
                <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
            <?php else: ?>
            <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="" id="postComment" method="post">
                    <div class="fieldset">
                        <ul class="form-list">
                            <li>
                                <div class="field">
                                    <div class="input-box aw-blog-comment-area">
                                        <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                        <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>
                <script type="text/javascript">
                    //<![CDATA[
                    var postComment = new VarienForm('postComment', false);
                    //]]>
                </script>
            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>
            <?php else: ?>
                <form action="<?php if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()): ?><?php else: ?><?php echo $this->getFormAction(); ?><?php endif; ?>" id="postComment" method="post">
                    <div class="fieldset">
                        <ul class="form-list">
                            <li>
                                <div class="field">
                                    <div class="input-box">
                                        <label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                        <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="input-box">
                                        <label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                        <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="field">
                                    <div class="input-box aw-blog-comment-area">
                                        <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:100%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <?php if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()): ?>
                        <div class="no-display">
                            <input type="text" name="noSpam" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('No Spam')) ?>" id="no-spam-post" class="input-text no-display required-entry" />
                        </div>
                    <?php endif; ?>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>

                        <button type="submit" title="<?php echo Mage::helper('blog')->__('Submit Comment') ?>" name="send" id="g-recaptcha-post" class="g-recaptcha-post button disabled" data-badge="bottomleft" data-size="invisible"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    //<![CDATA[
                    var postComment = new VarienForm('postComment', false);
                    //]]>
                </script>

                <?php $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()): ?>
                    <script>
                        // Prevent form to submit if hidden input has value
                        jQuery('#postComment').submit(function(e) {
                            if (jQuery('#no-spam-post').val() !== '') {
                                e.preventDefault();

                                window.history.back();
                            }
                        });

                        function onSubmitPost(token) {
                            setTimeout(function(){
                                jQuery('.g-recaptcha-post').attr('data-token', token);

                                if (jQuery('#no-spam-post').val() === '') {
                                    return new Promise(function (resolve, reject) {
                                        var dataForm = new VarienForm('postComment');
                                        var tokenHash = jQuery('.g-recaptcha-post').attr('data-token');

                                        if (tokenHash && tokenHash.length > 100) {
                                            jQuery('#no-spam-post').removeClass('required-entry');

                                            if (dataForm.validator && dataForm.validator.validate()){
                                                jQuery('#postComment').attr('action', '<?php echo $this->getAction() ?>');
                                                document.getElementById("postComment").submit();
                                            }
                                        }
                                    });
                                } else {
                                    window.history.back();
                                }
                            }, 500);
                        }

                        // Check if captcha container have loaded class, if not than captcha will be loaded
                        function loadCaptchaPost() {
                            setTimeout(function(){
                                // Fix for google recaptcha from 18 June
                                if ("NodeList" in window) {
                                    if (!NodeList.prototype.each && NodeList.prototype.forEach) {
                                        NodeList.prototype.each = NodeList.prototype.forEach;
                                    }
                                }

                                if (!jQuery('.captcha_container_post').length) {
                                    jQuery('#g-recaptcha-post').addClass('captcha_container_post');
                                    var captchaContainer = null;
                                    var loadCaptchaPostFunction = function() {
                                        captchaContainer = grecaptcha.render('g-recaptcha-post', {
                                            'sitekey': '<?php echo$this->helper('recaptcha')->getKey(); ?>',
                                            'callback': onSubmitPost
                                        });
                                    };

                                    loadCaptchaPostFunction();
                                }
                            }, 300);
                        };

                        // Once user insert a value, loadCaptchaContent will be called
                        jQuery('#postComment input').each(function(e) {
                            jQuery(this).on('change keyup blur input', function(e) {
                                loadCaptchaPost();
                            });
                        });

                        jQuery('.g-recaptcha-post').on('click', function(e) {
                            onSubmitPost();
                        });
                    </script>
                    <script src="https://www.google.com/recaptcha/api.js?onload=loadCaptchaPostFunction&render=explicit" async defer></script>
                <?php endif; ?>
            <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
