<?php
/** @var Mage_ConfigurableSwatches_Block_Catalog_Product_View_Type_Configurable_Swatches $this */

$_product    = $this->getProduct();
$_attribute = $this->getAttributeObj();
$_jsonConfig = $this->getJsonConfig();
$_config = json_decode($_jsonConfig);

$_swatchInnerWidth = $this->getSwatchInnerWidth();
$_swatchInnerHeight = $this->getSwatchInnerHeight();

$_attr = $_attribute->getProductAttribute();
$_attrCode = $_attr->getAttributeCode();
$_id = $_attribute->getAttributeId();

$_swatchArray = $_config->attributes->$_id;

$optionIds = array();
foreach ($_swatchArray->options as $sw) {
    $optionIds[] = $sw->id;
}

$swatchesData = Mage::getModel('blugento_swatches/swatches')
    ->getCollection()
    ->addFieldToFilter('option_id', array('in' => $optionIds));

$_selectedValue = Mage::getStoreConfig('blugento_configurableswatch/general/selected_option') ? Mage::getStoreConfig('blugento_configurableswatch/general/selected_option'): '';
$_preselectSingleSwatches = (int) ($this->getLayout()->getBlock('root')->getPreselectSingleSwatches() ?: 1);

/** @var Blugento_Swatches_Helper_Image $imageHelper */
$imageHelper = Mage::helper('blugento_swatches/image');

/** @var Blugento_Swatches_Helper_Data $helperData */
$helperData = Mage::helper('blugento_swatches');

$_tooltipInnerWidth = $helperData->getHoverSwatchImageWidth();
$_tooltipInnerHeight = $helperData->getHoverSwatchImageHeight();
?>
<dt class="swatch-attr">
    <label id="<?php echo $_attrCode ?>_label" class="required">
        <em>*</em><?php echo $_attribute->getLabel() ?>:
        <span id="select_label_<?php echo $_attrCode ?>" class="select-label"></span>
    </label>
</dt>
<dd class="swatch-attr<?php if ($_attribute->decoratedIsLast) echo ' last'; ?>">
    <div class="input-box">
        <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select no-display swatch-select">
            <option><?php echo $this->__('Choose an Option...') ?></option>
        </select>
        <ul id="configurable_swatch_<?php echo $_attrCode ?>"
            class="configurable-swatch-list clearfix blugento-swatches <?php echo $_selectedValue ?> preselect-swatch-<?php echo $_preselectSingleSwatches ?>"
            data-tooltip="<?php echo $helperData->isHoverSwatchImageEnabled() ?>"
        >
            <?php foreach ($_swatchArray->options as $_option): ?>
                <?php
                $_swatchData = $swatchesData->getItemByColumnValue('option_id', $_option->id);
                $_mode = $_swatchData->getMode();
                $_image = $_swatchData->getImageName();
                $_color = $_swatchData->getColor();
                $_getMedia = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
                $_optionCode = Mage::helper('configurableswatches')->getHyphenatedString($_option->label);
                $_swatchUrl = Mage::helper('configurableswatches/productimg')->getSwatchUrl($_product, $_option->label, $_swatchInnerWidth, $_swatchInnerHeight, $_swatchType);
                $_liClass = '';
                $_aClass = 'swatch-link swatch-link-' . $_attribute->getAttributeId();
                if ($_mode == 2 && $_image) {
                    $_liClass .= $_swatchType == 'media' ? ' is-media' : '';
                    $_aClass .= ' has-image';
                }
                
                if ($helperData->isHoverSwatchImageEnabled()) {
	                $image = str_replace('blugento_swatches/', '', $_image);
	
	                $swatchImage = $imageHelper->init($image)
		                ->constrainOnly(false)
		                ->keepAspectRatio(true)
		                ->keepFrame(true)
		                ->backgroundColor(array(255, 255, 255))
		                ->resize($_swatchInnerWidth, $_swatchInnerHeight);
	
	                $tooltipImage = $imageHelper->init($image)
		                ->constrainOnly(false)
		                ->keepAspectRatio(true)
		                ->keepFrame(true)
		                ->backgroundColor(array(255, 255, 255))
		                ->resize($_tooltipInnerWidth, $_tooltipInnerHeight);
                } else {
	                $swatchImage = $_getMedia . $_image;
                }
            
                ?>
                <li class="option-<?php echo $_optionCode ?><?php echo $_liClass ?>" id="option<?php echo $_option->id ?>" data-id="<?php echo $_option->id ?>">
                    <a href="javascript:void(0)"
                       name="<?php echo $_optionCode ?>"
                       data-id="<?php echo $_option->pid?>"
                       id="swatch<?php echo $_option->id ?>"
                       class="<?php echo $_aClass ?>"
                       title="<?php echo $_option->label ?>"
                       data-tooltip="<?php echo $helperData->isHoverSwatchImageEnabled() ?>"
                    >
                        <?php if ($_mode == 2 && $_image): ?>
                            <?php if ($helperData->isHoverSwatchImageEnabled()): ?>
	                            <span class="tooltip">
		                            <img src="<?php echo $tooltipImage ?>" alt="<?php echo $_option->label ?>" />
	                            </span>
	                        <?php endif; ?>
                            <span class="swatch-label" height="<?php echo $_swatchInnerHeight ?>">
                                <img src="<?php echo $swatchImage ?>" alt="<?php echo $_option->label ?>" width="<?php echo $_swatchInnerWidth - 2 ?>" height="<?php echo $_swatchInnerHeight - 2?>" />
                            </span>
                        <?php else: ?>
                            <?php if (Mage::getStoreConfig('configswatches/blugento_swatches/display_label') || ($_mode == 2 && $_image)): ?>
                                <span class="swatch-label with-label" style="background-color: #<?php echo $_color ?>; line-height: <?php echo $_swatchInnerHeight ?>px; min-width: <?php echo $_swatchInnerWidth ?>px;">
                                    <span style="height: <?php echo $_swatchInnerWidth ?>px;"><?php echo $_option->label ?></span>
                                </span>
                            <?php else: ?>
                                <?php if ($_color == ''): ?>
                                    <span class="swatch-label no-color" style="height: <?php echo $_swatchInnerHeight ?>px; line-height: <?php echo $_swatchInnerHeight ?>px; min-width: <?php echo $_swatchInnerWidth ?>px;">
                                        <span><?php echo $_option->label ?></span>
                                    </span>
                                <?php else: ?>
                                    <span class="swatch-label no-label" style="background-color: #<?php echo $_color ?>; height: <?php echo $_swatchInnerHeight ?>px; width: <?php echo $_swatchInnerWidth ?>px;"></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</dd>



