<?php
/**
 * @category    design
 * @package     rwd_default
 */
?>
<?php 
    $_item = $this->getItem();
    $_order = $this->getItem()->getOrder();
    
	$id = $_item->getProductId();
	
	if (Mage::helper('core')->isModuleEnabled('MindMagnet_Configurable') && $_item->getProductType() == 'configurable') {
		$id = Mage::getModel('catalog/product')->getIdBySku($_item->getSku());
	}
	
	$product = Mage::getModel('catalog/product')->load($id);
	$productPrice = $product->getPrice();
	$productSpecialPrice = $product->getSpecialPrice();
	
	$helper = Mage::helper('blugento_sales');
?>
<tbody>
<tr>
    <td class="cell-content product-info">
        <table class="table-product-details">
            <tr>
                <?php if($helper->imageOnEmailEnabled()): ?>
                    <td>
                        <div class="image-product">
	                        <a href="<?php echo $_item->getProduct()->getProductUrl(); ?>">
                                <img src="<?php echo $helper->getImageForEmail($_item); ?>"  width="80" height="auto" alt="<?php echo $_item->getName() ?>" />
	                        </a>
                        </div>
                    </td>
                <?php endif; ?>
                <td>
                    <div class="product-details">
                        <p class="product-name">
	                        <a href="<?php echo $_item->getProduct()->getProductUrl(); ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a>
                        </p>
                        <p class="sku"><span class="sku-name"><?php echo $this->__('SKU'); ?>:</span> <?php echo $this->escapeHtml($this->getSku($_item)) ?></p>
                        <?php if ($this->getItemOptions()): ?>
                            <dl style="margin:0; padding:0;">
                                <?php foreach ($this->getItemOptions() as $option): ?>
                                    <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
                                    <dd style="margin:0; padding:0 0 0 9px;">
                                        <?php echo nl2br($option['value']) ?>
                                    </dd>
                                <?php endforeach; ?>
                            </dl>
                        <?php endif; ?>
                        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
                        <?php if ($addInfoBlock) :?>
                            <?php echo $addInfoBlock->setItem($_item)->toHtml(); ?>
                        <?php endif; ?>

                        <?php try {
                            if (!Mage::getStoreConfig('sales_email/order/remove_delivery_time')) : ?>
                                <?php $delivery_time = Mage::getResourceModel('catalog/product')->getAttributeRawValue($_item->getProduct()->getId(), 'delivery_time', $_order->getStore());
                                if ($delivery_time) : ?>
                                    <p><?php echo $this->__('Delivery Time'), ': ', $delivery_time; ?></p>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php } catch (Exception $e) {} ?>

                        <?php echo $this->escapeHtml($_item->getDescription()) ?>
                    </div>
                </td>
            </tr>
        </table>
    </td>
    <td class="cell-content align-center"><?php echo $_item->getQtyOrdered()*1 ?></td>
    <td class="cell-content align-right">
	    <?php if ($productSpecialPrice && $_item->getPriceInclTax() == $productSpecialPrice) :
		    echo '<span style="display: block; text-decoration: line-through;">' . $_order->formatPrice($productPrice) . '</span>';
	    endif; ?>
		   
	    <?php echo $_order->formatPrice($_item->getPriceInclTax()*1) ?>
    </td>
    <td class="cell-content align-right">
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                        <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_item->getGiftMessageId())): ?>
    <tr>
        <td colspan="4" style="border-bottom:2px solid #CCCCCC; padding:5px 30px;">
            <strong style="color:#444444; font-size:12px;"><?php echo $this->__('Gift Message') ?></strong>
            <?php echo $this->__('From:'); ?> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?><br />
            <?php echo $this->__('To:'); ?> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?><br />
            <strong><?php echo $this->__('Message:'); ?></strong><br /><?php echo $this->escapeHtml($_giftMessage->getMessage()) ?>
        </td>
    </tr>
<?php endif; ?>
</tbody>
