<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper      = $this->helper('catalog/output');
    $_category    = $this->getCurrentCategory();
    $_imgHtml     = '';
    if ($_imgUrl  = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="' . $_imgUrl . '" data-src="' . $_imgUrl . '" alt="' . $this->escapeHtml($_category->getName()) . '" title="' . $this->escapeHtml($_category->getName()) . '" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
    $_description = $this->getCurrentCategory()->getDescription();
    $_categoryDescriptionTruncate = Mage::getStoreConfig('blugento_categoryshowcase/general/category_description_truncate');
    $_categoryDescriptionTruncateValue = Mage::getStoreConfig('blugento_categoryshowcase/general/category_description_truncate_value') ?: 600;
    $_removeCategoryDescription = Mage::getStoreConfig('blugento_seoenhancements/enhancements_group/remove_category_description');
    $_baseUrl = Mage::getBaseUrl();
    $_baseMedia = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
    $_baseMediaUrl = str_replace('/media', '', $_baseMedia);
    $_bannerWebp = Mage::getStoreConfig('blugento_cloudfront/blugento_cloudfront/active') &&
    Mage::getStoreConfig('blugento_cloudfront/blugento_cloudfront/webp_conversion') && ($_baseUrl != $_baseMediaUrl);
?>

<?php if ($this->getBackgroundImageUrl($_category)): ?>
	<div id="category-back-frame" style="background-image:<?php if ($_bannerWebp): ?> url('<?php echo $this->getBackgroundImageUrl($_category) ?>.webp'),<?php endif; ?> url('<?php echo $this->getBackgroundImageUrl($_category) ?>')"></div>
<?php endif ?>

<?php if ($_category->getBlugentoCategorySlider()) : ?>
	<div id="category-banner-group">
		<?php echo $this->getLayout()->createBlock('blugento_sliders/view')->setGroupCode($_category->getBlugentoCategorySlider())->setDisplayControls(1)->toHtml(); ?>
	</div>
<?php endif; ?>

<div class="page-title">
	<?php if (!Mage::helper('blugento_seoenhancements')->isChangePageAndMetaTitleOptionEnabled()) : ?>
	    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?>
	        <?php if (Mage::getStoreConfig('blugento_seoenhancements/enhancements_group/new_page_title')) : ?>
	            <?php echo $this->getLayout()->createBlock('blugento_seoenhancements/page_html_head')->setTemplate('blugento/seoenhancements/page/html/new_title.phtml')->toHtml(); ?>
	        <?php endif; ?>
	    </h1>
	<?php else: ?>
		<h1><?php echo $this->getLayout()->getBlockSingleton('blugento_seoenhancements/page_html_head')->changeCategoryFilterHOneTagTitle() ?: $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
	<?php endif; ?>
</div>

<div class="category-intro">
    <?php if ($_imgUrl): ?>
        <?php echo $_imgHtml ?>
    <?php endif; ?>
    <?php $currentPage = (int) Mage::App()->getRequest()->getParam('p'); ?>
    <?php if($_removeCategoryDescription && $currentPage > 1): ?>

    <?php else : ?>
        <div class="category-description <?php if ($_categoryDescriptionTruncate): ?> description-truncated<?php endif; ?> std" data-truncated-value="<?php echo $_categoryDescriptionTruncateValue ?>">
            <span class="description-content"><?php echo nl2br($_helper->categoryAttribute($_category, $_description, 'description')) ?></span>
            <span class="show-more"><?php echo $this->__('Read More') ?></span>
            <span class="show-less"><?php echo $this->__('Show less') ?></span>
        </div>
    <?php endif; ?>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if ($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif ($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php elseif($this->isSubcategoryProductsMode()): ?>
    <?php echo $this->getSubcategoryHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php elseif($this->isSubcategoryPageMode()): ?>
    <?php echo $this->getSubcategoryHtml() ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif($this->isSubcategoryMixedAll()): ?>
    <?php echo $this->getSubcategoryHtml() ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>
<?php elseif($this->isSubcategoryMode()): ?>
    <?php echo $this->getSubcategoryHtml() ?>
<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
