<?php
/**
 * This file is part of a Blugento Localizer e.V. module.
 *
 * @category  Blugento
 * @package   Blugento Localizer
 */
?>
<?php
/**
 * @var $this Blugento_Localizer_Block_Imprint_Content
 */
?>
<?php echo $this->getCompanyFirst() ?><br />
<?php if (strlen(trim($this->getCompanySecond()))): ?>
    <?php echo $this->getCompanySecond() ?><br />
<?php endif; ?>
<?php echo $this->getStreet() ?><br />
<?php echo $this->getZip() ?> <?php echo $this->getCity() ?>
<?php if (strlen(trim($this->getCountry()))): ?>
    <br /><?php echo $this->getCountry() ?>
<?php endif; ?>
