<?php
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();

?>
<h4 class="product-manufacturer"><?php echo $product->getAttributeText('manufacturer') ?></h4>
<h3 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h3>
<?php echo $this->getPriceHtml($product, empty($options)) ?>
<div class="description std">
    <div class="inner"><?php echo $this->escapeHtml($this->stripTags($product->getShortDescription())) ?></div>
</div>
<span class="label"><?php echo $this->__('Add comments') ?></span>
<textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" class="input-text" onfocus="focusComment(this)" onblur="focusComment(this)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Comment')) ?>"><?php echo ($this->escapeHtml($item->getDescription() ? $item->getDescription() : $this->helper('wishlist')->defaultCommentString())) ?></textarea>
<?php if ($this->getSortedChildren()): ?>
<div class="item-manage">
    <?php foreach ($this->getSortedChildren() as $childName): ?>
        <?php echo $this->getChildHtml($childName, false); ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
