<?php
/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php $_description = $this->getProduct()->getDescription(); ?>
<?php $breakType = Mage::getStoreConfig('blugento_theme/general_nl2br/enable'); ?>
<?php if($breakType == 1): ?>
    <?php if ($_description): ?>
        <div class="std">
            <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if($breakType == 2): ?>
    <?php if ($_description == strip_tags($_description)): ?>
        <div class="std">
            <?php echo nl2br($this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description')) ?>
        </div>
    <?php else: ?>
        <div class="std">
            <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description') ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if($breakType == 3): ?>
    <?php if ($_description): ?>
        <div class="std">
            <?php echo nl2br($this->helper('catalog/output')->productAttribute($this->getProduct(), $_description, 'description')) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
