<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_New
 */
?>

<?php
$_productListTaxMode = (int) ($this->getLayout()->getBlock('root')->getProductListTaxMode() ?: 1);
$_productListImageResize = (int) ($this->getLayout()->getBlock('root')->getProductListImageResize() ?: 1);
$_productListItems = (int) ($this->getLayout()->getBlock('root')->getProductListItems() ?: 2);
?>

<?php
$_productCollection = $this->getProductCollection();
if ( ! $_productCollection) {
    return;
}
$_outputHelper = $this->helper('catalog/output');
$_imageHelper = $this->helper('catalog/image');
/* @var $_taxHelper Mage_Tax_Helper_Data */
$_taxHelper = $this->helper('tax');

$_taxInfo = '';
if ($_taxHelper->displayPriceExcludingTax()) {
    $_taxInfo = '<span class="tax-details">' . $this->__('Excluding tax') . '</span>';
} else {
    $_taxInfo = '<span class="tax-details">' . $this->__('Including tax') . '</span>';
}

$rightNow = time();
$_products = array();

foreach ($_productCollection as $_product) {
    $_products[$_product->getId()] = array(
        'product'           => $_product,
        'id'                => $_product->getId(),
        'sku'               => $_product->getSku(),
        'url'               => $_product->getProductUrl(),
        'image'                     => (string) $_imageHelper->init($_product, 'small_image')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(300, 300),
        'imageSquare'               => (string) $_imageHelper->init($_product, 'small_image')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(400, 400),
        'imageWidthResized'         => (string) $_imageHelper->init($_product, 'small_image')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(300, 400),
        'imageHeightResized'        => (string) $_imageHelper->init($_product, 'small_image')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(300, 200),
        'imageHover'                => (string) $_imageHelper->init($_product, 'thumbnail')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(300, 300),
        'imageSquareHover'          => (string) $_imageHelper->init($_product, 'thumbnail')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(400, 400),
        'imageWidthResizedHover'    => (string) $_imageHelper->init($_product, 'thumbnail')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(300, 400),
        'imageHeightResizedHover'   => (string) $_imageHelper->init($_product, 'thumbnail')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(300, 200),
        'image@2x'                  => (string) $_imageHelper->init($_product, 'small_image')->keepFrame(true)->backgroundColor($_productImageBackgroundColorToHex)->resize(600),
        'image@2x'          => (string) $_imageHelper->init($_product, 'small_image')->keepFrame(true)->resize(550),
        'image_alt'         => $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true),
        'name'              => $_outputHelper->productAttribute($_product, $_product->getName() , 'name'),
        'name_stripped'     => $this->stripTags($_product->getName(), null, true),
        'manufacturer'      => $_product->getAttributeText('manufacturer'),
        'manufacturer_id'   => $_product->getManufacturer(),
        'short_description' => strip_tags($_outputHelper->productAttribute($_product, $_product->getShortDescription(), 'short_description')),
        'price'             => trim($this->getPriceHtml($_product, true, '-new')),
        'is_saleable'       => $_product->isSaleable(),
        'add_to_cart'       => $this->getAddToCartUrl($_product),
        'whishlist_url'     => ($this->helper('wishlist')->isAllow()) ? $this->helper('wishlist')->getAddUrl($_product) : '',
        'compare_url'       => $this->getAddToCompareUrl($_product),
        'reviews'           => ($_product->getRatingSummary()) ? $this->getReviewsSummaryHtml($_product, 'short') : '',
        'is_new'            => ($_product->getNewsFromDate() || $_product->getNewsToDate()) &&
                               (
                                   $rightNow >= strtotime($_product->getNewsFromDate()) && $rightNow <= strtotime($_product->getNewsToDate()) ||
                                   $rightNow >= strtotime($_product->getNewsFromDate()) && is_null($_product->getNewsToDate()) ||
                                   $rightNow <= strtotime($_product->getNewsToDate()) && is_null($_product->getNewsFromDate())
                               ),
        'is_sale'           => $_product->getSpecialPrice() &&
                               (
                                   $rightNow >= strtotime($_product->getSpecialFromDate()) && $rightNow <= strtotime($_product->getSpecialToDate()) ||
                                   $rightNow >= strtotime($_product->getSpecialFromDate()) && is_null($_product->getSpecialToDate()) ||
                                   $rightNow <= strtotime($_product->getSpecialToDate()) && is_null($_product->getSpecialFromDate())
                               ),
        'tax'               => ($_productListTaxMode == 1) ? $_taxInfo : ''
    );
    $_products[$_product->getId()]['has_labels'] = $_products[$_product->getId()]['is_new'] || $_products[$_product->getId()]['is_sale'];
}
?>
<?php if (count($_products)): ?>
<h2 class="subtitle"><?php echo $this->__('New products') ?></h2>
<ul class="products-grid grid-6">
    <?php foreach ($_products as $_k => $_p): ?>
    <li class="item">
        <div class="item-inner">
            <a href="<?php echo $_p['url'] ?>" title="<?php echo $_p['image_alt'] ?>" class="product-image product-image-hover-<?php echo $_productListHover ?>">
                <?php if ($_productListImageResize == 1): ?>
                    <img class="product-img" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo $_p['image'] ?>" data-srcset="<?php echo $_p['image'] . ' 1x, ' . $_p['image@2x'] . ' 2x'; ?>" alt="<?php echo $_p['image_alt'] ?>" width="300" height="300" id="product-collection-image-<?php echo $_p['id'] ?>" />
                    <?php if ($_productListHover == 1): ?>
                        <img class="product-img-hover" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo $_p['imageHover'] ?>" data-srcset="<?php echo $_p['imageHover'] . ' 1x, ' . $_p['imageHover@2x'] . ' 2x'; ?>" alt="<?php echo $_p['image_alt'] ?>" width="300" height="300" id="product-collection-image-hover-<?php echo $_p['id'] ?>" />
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($_productListImageResize == 2): ?>
                    <img class="product-img" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo $_p['imageWidthResized'] ?>" data-srcset="<?php echo $_p['imageWidthResized'] . ' 1x, ' . $_p['imageWidthResized@2x'] . ' 2x'; ?>" alt="<?php echo $_p['image_alt'] ?>" width="300" height="400" id="product-collection-image-<?php echo $_p['id'] ?>" />
                    <?php if ($_productListHover == 1): ?>
                        <img class="product-img-hover" src="<?php echo $_p['imageWidthResizedHover'] ?>" data-src="<?php echo $_p['imageWidthResizedHover'] ?>" data-srcset="<?php echo $_p['imageWidthResizedHover'] . ' 1x, ' . $_p['imageWidthResizedHover@2x'] . ' 2x'; ?>" alt="<?php echo $_p['image_alt'] ?>" width="300" height="400" id="product-collection-image-hover-<?php echo $_p['id'] ?>" />
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($_productListImageResize == 3): ?>
                    <img class="product-img" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo $_p['imageHeightResized'] ?>" data-srcset="<?php echo $_p['imageHeightResized'] . ' 1x, ' . $_p['imageHeightResized@2x'] . ' 2x'; ?>" alt="<?php echo $_p['image_alt'] ?>" width="300" height="200" id="product-collection-image-<?php echo $_p['id'] ?>" />
                    <?php if ($_productListHover == 1): ?>
                        <img class="product-img-hover" src="<?php echo $_p['imageHeightResized'] ?>" data-src="<?php echo $_p['imageHeightResized'] ?>" data-srcset="<?php echo $_p['imageHeightResized'] . ' 1x, ' . $_p['imageHeightResized@2x'] . ' 2x'; ?>" alt="<?php echo $_p['image_alt'] ?>" width="300" height="200" id="product-collection-image-hover-<?php echo $_p['id'] ?>" />
                    <?php endif; ?>
                <?php endif; ?>
            </a>
            <?php if ($_p['manufacturer_id']): ?>
                <div class="mnfr-<? echo $_p['manufacturer_id'] ?> mnfr-list"></div>
            <?php endif; ?>
            <div class="product-box">
                <div class="product-info">
                    <?php if ($_p['manufacturer']): ?>
                        <h3 class="product-manufacturer"><?php echo $_p['manufacturer'] ?></h3>
                    <?php endif; ?>
                    <h2 class="product-name">
                        <a href="<?php echo $_p['url'] ?>" title="<?php echo $_p['name_stripped'] ?>"><?php echo $_p['name'] ?></a>
                    </h2>
                    <?php echo $_p['price'] ?>
                    <?php echo $_p['tax'] ?>
                </div>
            </div>
            <?php if ($_p['has_labels']): ?>
                <div class="product-badges">
                    <?php if ($_p['is_new']): ?>
                        <div class="badge badge--new"><?php echo $this->__('New!') ?></div>
                    <?php endif; ?>
                    <?php if ($_p['is_sale']): ?>
                        <div class="badge badge--sale"><?php echo $this->__('Sale!') ?></div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
