<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Scheckout
 */
?>
<script type="text/javascript">
    //This code closed fancybox with iframe
    //Fancybox had iframe with 3D-secure form and button for complete
    //After 3D-secure complete this code cosed fancybox with iframe
    if (window.parent.jQuery.fancybox.isOpen) {
        window.parent.jQuery.fancybox.close();
    }
</script>