<?php if ($this->getCurrencyCount() > 1): ?>
<div class="form-currency <?php echo $this->getClass() ?>">
    <select onchange="window.location.href=this.value" name="custom-currency-selector">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if ($_code == $this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>><?php echo $_code ?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>

