
<div class="col-main">
    <?php if ($this->showSentMsg): ?>
        <ul class="messages">
            <li class="success-msg">
                <ul>
                    <li>Your message was submitted and will be responded as soon as possible. Thank you for reporting.</li>
                </ul>
            </li>
        </ul>
    <?php endif; ?>
    <?php if ($this->showSendForm): ?>
        <div class="page-title">
          <h1>There has been an error processing your request</h1>
        </div>
        <ul class="messages">
            <li class="note-msg">
                <ul>
                    <li>We are currently experiencing some technical issues. We apologize for the inconvenience and will contact you shortly to resolve the issue. To help us serve you please fill in the form below.</li>
                </ul>
            </li>
        </ul>
        <?php if ($this->showErrorMsg): ?>
            <ul class="messages">
                <li class="error-msg">
                    <ul>
                        <li>Please fill all required fields with valid information</li>
                    </ul>
                </li>
            </ul>
        <?php endif; ?>
        <form action="<?php echo "{$this->getBaseUrl(true)}errors/report.php?id={$this->reportId}" ?>" method="post" id="form-validate">
            <fieldset class="fieldset">
                <h2>Personal Information</h2>
                <ul class="form-list form-list--inline group-select">
                    <li class="fields">
                        <div class="field">
                            <label for="firstname" class="required"><em>*</em>First Name</label>
                            <div class="input-box"><input type="text" name="firstname" id="firstname" value="<?php echo $this->postData['firstName'] ?>" title="First Name" class="required-entry input-text" /></div>
                        </div>
                        <div class="field">
                            <label for="lastname" class="required"><em>*</em>Last Name </label>
                            <div class="input-box"><input type="text" name="lastname" id="lastname" value="<?php echo $this->postData['lastName'] ?>" title="Last Name" class="required-entry input-text" /></div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="firstname" class="required"><em>*</em>Email Address</label>
                            <div class="input-box"><input type="text" name="email" id="email_address" value="<?php echo $this->postData['email'] ?>" title="Email Address" class="validate-email required-entry input-text" /></div>
                        </div>
                        <div class="field">
                            <label for="firstname">Telephone</label>
                            <div class="input-box"><input type="text" name="telephone" id="telephone" value="<?php echo $this->postData['telephone'] ?>" title="Telephone" class="input-text" /></div>
                        </div>
                    </li>
                    <li>
                        <div class="input-box">
                            <label for="firstname">Comment</label>
                            <div class="input-box"><textarea name="comment" cols="5" rows="3" class="input-text"><?php echo $this->postData['comment'] ?></textarea></div>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set form-buttons btn-only">
                <button name="submit" class="button" type="submit"><span><span>Submit</span></span></button>
                <p class="required">* Required Fields</p>
            </div>
        </form>
    <?php elseif ('' == $this->reportAction): ?>
        <h1>Exception printing is disabled by default for security reasons.</h1>
    <?php endif; ?>

    <?php if ($this->reportAction == 'print'): ?>
      <h1>We will be back soon!</h1>
      <h3>Sorry for the inconvenience. <br > We'll be back up and running as fast as possible.</h3>
      <div class="trace-container" style="display: none;">
          <div class="trace">
              <pre><?php echo $this->reportData[0] ?><br />
                  <strong>Trace:</strong>
                  <?php echo htmlspecialchars($this->reportData[1]) ?><br />
              </pre>
          </div>
      </div>
    <?php endif; ?>
    <?php if ($this->reportId && $this->reportUrl): ?>
        <div style="display: none;">Error log record number: <span class="highlight"><?php echo $this->reportId ?></span></div>
    <?php endif; ?>
</div>

