<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Subtotal
 * @see Mage_Tax_Block_Checkout_Subtotal
 */
?>
<?php if ($this->displayBoth()): ?>
<tr>
    <th style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan() ?>">
        <?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr>
    <th style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan() ?>">
        <?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else: ?>
<tr>
    <th style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan() ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </th>
    <td style="<?php echo $this->getStyle() ?>">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif; ?>
