<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Tax
 * @see Mage_Tax_Block_Checkout_Tax
 */
?>
<?php
if (Mage::helper('core')->isModuleEnabled('MW_Onestepcheckout') && !Mage::getStoreConfig('onestepcheckout/config/enabled')) {
	$_checkoutCartTotalHideTax = (int) ($this->getLayout()->getBlock('root')->getCheckoutCartTotalHideTax() ?: 2);
	if ($_checkoutCartTotalHideTax == 1) {
		return;
	}
}

$_value = $this->getTotal()->getValue();
$_style = $this->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary() && $_value != 0): ?>
<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>
        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
            <th style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan() ?>">
                <?php echo $this->escapeHtml($rate['title']); ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?php echo (float)$rate['percent'] ?>%)
                <?php endif; ?>
            </th>
            <?php if ($isFirst): ?>
                <td style="<?php echo $_style ?>" rowspan="<?php echo count($rates) ?>">
                    <?php echo $this->helper('checkout')->formatPrice($amount) ?>
                </td>
            <?php endif; ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
    <?php $weees = $this->getAllWeee(); ?>
    <?php foreach ($weees as $weeeTitle => $weeeAmount): ?>
    <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
        <th style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan() ?>">
            <?php echo $this->escapeHtml($weeeTitle) ?>
        </th>
        <td style="<?php echo $_style ?>" rowspan="1">
            <?php echo $this->helper('checkout')->formatPrice($weeeAmount) ?>
        </td>
    </tr>
    <?php endforeach; ?>
<?php endif; ?>
<tr id="vat-summary-total" <?php if ($this->helper('tax')->displayFullSummary() && $_value != 0): ?> class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter ?>')"<?php endif; ?>>
    <th style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan() ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif; ?>
    </th>
    <td style="<?php echo $_style ?>">
        <?php echo $this->helper('checkout')->formatPrice($_value) ?>
    </td>
</tr>
