<?php
$_filter = $this->getFilter();
$_label = $this->stripTags($_filter->getLabel());

$_swatchInnerWidth = $this->getSwatchInnerWidth();
$_swatchInnerHeight = $this->getSwatchInnerHeight();
$_swatchOuterWidth = $this->getSwatchOuterWidth();
$_swatchOuterHeight = $this->getSwatchOuterHeight();

$_lineHeight = $_swatchOuterHeight + 2;

$_swatchUrl = $this->getSwatchUrl();
?>

<li class="swatch-current">
    <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span>
    <span class="value">
        <span class="swatch-link">
            <span class="swatch-label">
                <img src="<?php echo $_swatchUrl; ?>" srcset="<?php echo $_swatchUrl; ?> 1x, <?php echo $_swatchUrl; ?> 2x" alt="<?php echo $_label; ?>" title="<?php echo $_label ?>" width="<?php echo $_swatchInnerWidth ?>" height="<?php echo $_swatchInnerHeight ?>" />
            </span>
        </span>
    </span>
    <?php if ($clearLinkUrl = $_filter->getClearLinkUrl()): ?>
        <a class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>"><?php echo $this->__('Previous') ?></a>
        <a class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
    <?php else: ?>
        <a class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove')) ?>"><?php echo $this->__('Remove') ?></a>
    <?php endif; ?>
</li>
