<?php
if (($files = Mage::getModel('staempfli_productattachment/file')->getFilesByProductId($this->getProduct()->getId(), Mage::app()->getStore()->getStoreId(), false, true)->getData()) && count($files) > 0):
    $helper = $this->helper('staempfli_productattachment');
    $dir = Mage::getBaseUrl('media').$helper::UPLOAD_DIR;
    ?>
    <ul>
        <?php foreach ($files as $file): ?>
            <li class="tab_list_element">
                <!-- <a id="mediathek" class="headline active"><?php echo $this->__('Mediathek') ?></a> -->
                <div id="tab-mediathek" class="tabs_content">
                        <div class="mediathek">
                            <i class="fa fa-file-o fa-2x"></i> <a href="<?php echo $dir.DS.$file['path']; ?>" target="_blank"><?php echo $file['title'] ? $file['title'] : explode('.', $file['filename'])[0] ;?></a>
                        </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
