<?php $l = $this->getWishlistItemsCount() ?>
<div style="padding:15px;">
<table cellspacing="0" cellpadding="0" border="0" width="650">
    <tr>
    <?php $i = 0; foreach ($this->getWishlistItems() as $item): $i++ ?>
        <?php /* @var $item Mage_Wishlist_Model_Item */ ?>
        <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
        <?php $_product = $item->getProduct(); ?>
        <?php
        /* @var $this Mage_Wishlist_Block_Share_Email_Items */
        $_imageHelper = $this->helper('catalog/image');
        $image        = $_imageHelper->init($_product, 'small_image')->resize(135);
        $image2x      = $_imageHelper->init($_product, 'small_image')->resize(270);
        ?>
        <td width="32%">
            <p align="center" style="font-size:12px;"><a href="<?php echo $this->getProductUrl($_product) ?>"><img src="<?php echo $image; ?>" srcset="<?php echo $image . ' 1x,' . $image2x . ' 2x'; ?>" style="border:1px solid #ccc;" width="135" height="135" alt="" /></a></p>
            <p align="center" style="font-size:12px;"><a href="<?php echo $this->getProductUrl($_product) ?>" style="color:#203548;"><strong style="font-size: 14px;"><?php echo $this->escapeHtml($_product->getName()) ?></strong></a></p>
            <?php if($this->hasDescription($item)): ?><p align="center" style="font-size:12px;"><?php echo $this->__('Comment') ?>:<br /><?php echo $this->getEscapedDescription($item) ?></p><?php endif; ?>
            <p align="center" style="font-size:12px;"><a href="<?php echo $this->getProductUrl($_product) ?>" style="color:#1E7EC8;"><?php echo $this->__('View Product') ?></a> <small>
            <?php if ($_product->getIsSalable()): ?>|</small> <a href="<?php echo $this->getSharedItemAddToCartUrl($item) ?>" style="color:#1E7EC8;"><strong><?php echo $this->__('Add to Cart') ?></strong></a><?php endif;?>
            </p></td>
        <?php if ($i%3!=0): ?>
            <td width="2%"></td>
        <?php else: ?>
           </tr>
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
            <?php if ($i<$l): ?>
               <tr>
            <?php endif ?>
        <?php endif ?>
    <?php endforeach ?>
</table>
</div>
