<?php /** @var $this Blugento_GoogleTagManager_Block_GtmCode */
if (!($isEnabled = $this->isEnabled())) {
	return;
}

$accountId 	= $this->getAccountId();
$categoryId = $this->getCategory();
$categories = Mage::getModel('gdprcookies/system_config_source_categories')->toOptionArray();

foreach ($categories as $category) {
    if ($category['value'] == $categoryId) {
        $scriptCategory = strtolower($category['label']);
    }
}

$scriptCategory = str_replace('analytics', 'statistics', $scriptCategory);
$cookie 		= Mage::getSingleton('core/cookie')->get($scriptCategory);
?>
<?php if ($isEnabled && $accountId) : ?>
	<script>
	(function($) {
		$(document).ready(function() {
			function gtmSnippet() {
				(function(w,d,s,l,i) {
					w[l] = w[l] || [];
					w[l].push({
					'gtm.start': new Date().getTime(),
					event: 'gtm.js'
					});
					var f = d.getElementsByTagName(s)[0],
						j = d.createElement(s),
						dl = l != 'dataLayer' ? '&l=' + l : '';
					j.async = true;
					j.src = '//www.googletagmanager.com/gtm.js?id=' + i + dl;
					f.parentNode.insertBefore(j,f);
				})(window, document, 'script', 'dataLayer', '<?php echo $accountId ?>');
			}

			if (!$('body').hasClass('gdpr-enabled') || '<?php echo $categoryId ?>' == '1' || '<?php echo $cookie ?>' == 'yes') {
				gtmSnippet();
			} else {
				// Accept only selected cookies
				$('#accept-selected-cookies').on('click', function(e) {
					if ($('#<?php echo $scriptCategory ?>').is(':checked') || $('#<?php echo $scriptCategory ?>').is('[readonly]')) {
						gtmSnippet();
					}
				});

				// Accept all cookies
				$('#accept-all-cookies').on('click', function(e) {
					gtmSnippet();
				});

				if ('<?php echo $scriptCategory ?>' == 'necessary') {
					gtmSnippet();
				}
			}
		});
	})(jQuery);
	</script>
<?php endif; ?>
