<?php $idTrack = $this->getRequest()->getParam('id') ? $this->getRequest()->getParam('id') : null; ?>
<?php
$description = $this->__('Success');
if (preg_match('/O/',$idTrack)) {
    $description = $this->__('Order Place Success');
}
if (preg_match('/C/',$idTrack)) {
    $description = $this->__('Contact Success');
}
if (preg_match('/W/',$idTrack)) {
    $description = $this->__('Website Success');
}
if (preg_match('/CU/',$idTrack)) {
    $description = $this->__('Success');
}
?>
<?php if ($idTrack) : ?>
    <iframe height='1' width='1' scrolling='no' marginheight='0' marginwidth='0' frameborder='0' src='//event.2performant.com/events/leadcheck?campaign_unique=dcb3d4e2d&confirm=6c7f1514d12d9776&description=<?php echo $description; ?>&transaction_id=<?php echo $idTrack; ?>'></iframe>
<?php endif; ?>
