<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_StoreCredit
 */
?>
<?php /** @var $this Amasty_StoreCredit_Block_Adminhtml_Customer_Edit_Tab_CustomerBalance_Balance_History */ ?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-account"><?php echo $this->__('Transaction History')?></h4>
	</div>
	<div class="fieldset">
			<?php echo $this->getChildHtml('history_grid')?>
	</div>
</div>
