<?php
/**
 * Customer forgot password form template
 *
 * @see Mage_Customer_Block_Account_Forgotpassword
 */
?>
<?php $_newRegisterLayout = (int) ($this->getLayout()->getBlock('root')->getMyAccountRegisterNewLayout() ?: 2);
?>
<?php if ($_newRegisterLayout == 2) : ?>
	<div class="page-title">
		<h1><?php echo $this->__('Forgot Your Password?') ?></h1>
	</div>
	<?php echo $this->getMessagesBlock()->toHtml() ?>
	<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
		<div class="fieldset">
			<h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
			<p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
			<ul class="form-list">
				<li>
					<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
					<div class="input-box">
						<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
					</div>
				</li>
				<?php echo $this->getChildHtml('form.additional.info'); ?>
			</ul>
		</div>
		<div class="buttons-set">
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			<p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
			<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
		</div>
	</form>
	<script type="text/javascript">
			//<![CDATA[
			var dataForm = new VarienForm('form-validate', true);
			//]]>
	</script>
<?php elseif ($_newRegisterLayout == 1) : ?>
	<div class="row">
		<div class="col-6 col-sm-12 center">
			<div class="account-forgotpassword">
			    <div class="account-forgotpassword-wrapper">
				    <div class="page-title">
					    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
				    </div>
				    <?php echo $this->getMessagesBlock()->toHtml() ?>
				    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
					    <div class="fieldset">
						    <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
						    <ul class="form-list form-list--horizontal">
							    <li>
								    <div class="field">
									    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
									    <div class="input-box">
										    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
									    </div>
								    </div>
							    </li>
							    <?php echo $this->getChildHtml('form.additional.info') ?>
						    </ul>
					    </div>
					    <div class="buttons-set">
						    <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
						    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
						    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
					    </div>
				    </form>
				    <script>
						    //<![CDATA[
						    var dataForm = new VarienForm('form-validate', true);
						    //]]>
				    </script>
			    </div>
			</div>
		</div>
	</div>
<?php endif; ?>