<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to
 * newer versions in the future.
 *
 * @category    Blugento
 * @package     Blugento_Campaign
 * @author      Ciprian Mariuta <ciprian.mariuta@blugento.ro>
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

class Blugento_Campaign_Block_Adminhtml_Campaign_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    protected function _prepareLayout()
    {
        return parent::_prepareLayout();
    }

    protected function _prepareForm()
    {
        $form = new Varien_Data_Form(array(
            'id' => 'edit_form',
            'action' => $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))),
            'method' => 'post'
        ));
        $form->setUseContainer(true);
        $this->setForm($form);

        $campaignData = Mage::registry('campaign_data');

        $fieldsetGeneral = $form->addFieldset('campaign_general_form', array('legend' => Mage::helper('blugento_campaign')->__('Campaign Landing Page - General')));
        $this->_addElementTypes($fieldsetGeneral);

        $fieldsetGeneral->addField(
            'name',
            'text',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Name'),
                'class' => 'required-entry',
                'required' => true,
                'name' => 'name',
            )
        );

        $message = Mage::helper('blugento_campaign')->__('e.g. <b>blackfriday</b> or <b>bf2019</b>.') . ' ' . Mage::helper('blugento_campaign')->__('Will be autogenerated if empty.');

        $fieldsetGeneral->addField(
            'code',
            'text',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Code'),
                'name' => 'code',
                'after_element_html' => $message
            )
        );

        $message = Mage::helper('blugento_campaign')->__('Choose product category that will populate the campaign page.');

        $fieldsetGeneral->addField(
            'associated_category',
            'select',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Associated Category'),
                'name' => 'associated_category',
                'class' => 'required-entry',
                'required' => true,
                'values' => Mage::getSingleton('blugento_campaign/system_config_source_category')->toOptionArray(),
                'after_element_html' => $message
            )
        );

        $fieldsetGeneral->addField(
            'cms_page',
            'select',
            array(
                'label' => Mage::helper('blugento_campaign')->__('CMS Page'),
                'name' => 'cms_page',
                'values' => Mage::getSingleton('blugento_campaign/system_config_source_page')->toOptionArray(),
                'class' => 'required-entry',
                'required' => true,
            )
        );

        $fieldsetGeneral->addField(
            'layout',
            'select',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Layout'),
                'name' => 'layout',
                'values' => Mage::getSingleton('blugento_campaign/system_config_source_layout')->toOptionArray(),
                'after_element_html' => Mage::getSingleton('blugento_campaign/system_config_source_layouttooltip')->getTooltipHtml()
            )
        );

        $fieldsetGeneral->addField(
            'show_out_of_stock',
            'select',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Display Out of Stock Products'),
                'name' => 'show_out_of_stock',
                'values' => Mage::getSingleton('adminhtml/system_config_source_yesno')->toOptionArray(),
            )
        );

        if ($campaignData['shortcode']) {
            $message = '<br><b>' . Mage::helper('blugento_campaign')->__('This shortcode must be inserted in CMS Page content.') . '</b>';
        } else {
            $message = '<br>' . Mage::helper('blugento_campaign')->__('Shortcode will be auto-generated after saving the campaign.');
        }

        $fieldsetGeneral->addField(
            'shortcode',
            'label',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Shortcode'),
                'name' => 'shortcode',
                'after_element_html' => $message
            )
        );

        $fieldsetActive = $form->addFieldset('campaig_nactive_form', array('legend' => Mage::helper('blugento_campaign')->__('Campaign Landing Page - Activation')));
        $this->_addElementTypes($fieldsetActive);

        $fieldsetActive->addField(
            'status',
            'select',
            array(
                'label' => Mage::helper('blugento_campaign')->__('Status'),
                'name' => 'status',
                'values' => Mage::getSingleton('blugento_campaign/system_config_source_status')->toOptionArray(),
            )
        );

        $dateTimeFormat = Mage::app()->getLocale()->getDateTimeFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT);
        $fieldsetActive->addField(
            'start_date',
            'datetime',
            array(
                'name' => 'start_date',
                'label'     => Mage::helper('blugento_campaign')->__('Start Date'),
                'image' => $this->getSkinUrl('images/grid-cal.gif'),
                'input_format' => $dateTimeFormat,
                'format' => $dateTimeFormat,
                'time' => true,
            )
        );

        $fieldsetActive->addField(
            'end_date',
            'datetime',
            array(
                'label'     => Mage::helper('blugento_campaign')->__('End Date'),
                'name' => 'end_date',
                'image' => $this->getSkinUrl('images/grid-cal.gif'),
                'input_format' => $dateTimeFormat,
                'format' => $dateTimeFormat,
                'time' => true,
            )
        );

        if (Mage::getSingleton('adminhtml/session')->getCampaignData()) {
            $form->setValues(Mage::getSingleton('adminhtml/session')->getCampaignData());
            Mage::getSingleton('adminhtml/session')->setCampaignData(null);
        } elseif (Mage::registry('campaign_data')) {
            $form->setValues(Mage::registry('campaign_data')->getData());
        }
        return parent::_prepareForm();
    }
}