<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php if (count($this->getStores()) > 1): ?>
<div class="switch-languages">
    <ul class="list list--links list--horizontal">
        <?php foreach ($this->getStores() as $_lang): ?>
            <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' list__item--selected' : '' ?>
            <li class="list__item<?php echo $_selected ?>">
                <?php if ($_selected): ?>
                    <?php echo $this->escapeHtml($_lang->getName()) ?>
                <?php else: ?>
                    <a href="<?php echo $_lang->getCurrentUrl() ?>"><?php echo $this->escapeHtml($_lang->getName()) ?></a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

