<?php
/**
 * Blugento Billing Attributes
 *
 * Copyright (C) 2015-2016 Blugento <contact@blugento.com>
 * LICENSE: GNU General Public License for more details <http://opensource.org/licenses/gpl-license.php>
 *
 * @package Blugento_Billing
 * @author Simona Trifan <simona.plesuvu@mindmagnetsoftware.com>
 * @link http://www.blugento.com
 */
?>

<?php
$_checkoutShippingAddressLayout = (int) ($this->getLayout()->getBlock('root')->getCheckoutShippingAddressLayout() ?: 1);
$_checkoutUseBillingShippingAddressAboveForm = (int) ($this->getLayout()->getBlock('root')->getCheckoutUseBillingShippingAddressAboveForm() ?: 1);
?>

<?php
$customer = Mage::getSingleton('customer/session')->getCustomer();
$customerId = Mage::getSingleton('customer/session')->getCustomer();
$customer = Mage::getModel('customer/customer')->load($customerId->getId());
$data = array();

/* @var Blugento_Billing_Helper_Data $billHelper */
$billHelper = Mage::helper('blugento_billing');
$_checkoutNewLayOut = (int) ($this->getLayout()->getBlock('root')->getCheckoutViewNewLayout() ?: 2);

$storeId = Mage::app()->getStore()->getStoreId();

$phoneMinLength = Mage::getStoreConfig('blugento_billing/fields_config/phone_min_length', $storeId);
$phoneMaxLength = Mage::getStoreConfig('blugento_billing/fields_config/phone_max_length', $storeId);
$streetAddressMaxLength = Mage::getStoreConfig('blugento_billing/fields_config/street_address_max_length', $storeId);
?>
<?php if ($_checkoutNewLayOut == 2) : ?>
	<form id="co-shipping-form" action="">
		<ul class="form-list form-list--horizontal">
			<?php if ($this->customerHasAddresses()): ?>
				<li class="wide">
					<label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
					<div class="input-box">
						<?php if ($_checkoutShippingAddressLayout == 2): ?>
							<ul id="listAddressShipping" class="list--address">
								<?php $i = 0; ?>
								<?php foreach ($customer->getAddresses() as $address): ?>
									<?php $data = $address->toArray(); ?>
									<?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']); ?>
									<li onclick="Blugento.Checkout.setShippingAddress(this, <?php echo $data['entity_id'] ?>);" id="blugento-shipping-address-<?php echo $data['entity_id'] ?>">
										<?php echo $data['firstname'] . ' ' . $data['lastname'] ?><br />
										<?php echo $data['street'] ?><br />
										<?php echo $data['city'] . ',' . $data['region'] . ',' . $data['postcode'] ?><br />
										<?php echo $country_name ?><br />
										<?php echo $data['telephone'] ?>
									</li>
									<?php $i++; ?>
								<?php endforeach; ?>
							</ul>
							<div class="input-box" style="display: none;">
								<?php echo $this->getAddressesHtmlSelect('shipping') ?>
							</div>
						<?php else: ?>
							<div class="input-box">
								<?php echo $this->getAddressesHtmlSelect('shipping') ?>
							</div>
						<?php endif; ?>
					</div>
				</li>
			<?php endif; ?>
			<?php if ($_checkoutUseBillingShippingAddressAboveForm == 1): ?>
				<li class="control">
					<input
						type="checkbox"
						name="shipping[same_as_billing]"
						id="shipping:same_as_billing"
						value="1"
						<?php if ($this->getAddress()->getSameAsBilling()): ?>
							checked="checked"
						<?php endif; ?>
						title="<?php echo $this->__('Use Billing Address') ?>"
						onclick="shipping.setSameAsBilling(this.checked)"
						class="checkbox"
					/>
					<label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
				</li>
			<?php endif; ?>
			<li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display: none;"<?php endif ?>>
				<fieldset>
					<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
					<ul>
						<li class="fields">
							<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
						</li>
						<li class="fields shipping_company">
							<div class="field">
								<label for="shipping:company"><?php echo $this->__('Company') ?></label>
								<div class="input-box">
									<input
										type="text"
										name="shipping[company]"
										id="shipping:company"
										value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
										title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>"
										class="input-text"
									/>
								</div>
							</div>
						</li>
						
						<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
						<li class="wide">
							<div class="field">
								<label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
								<div class="input-box">
									<input
										type="text"
										name="shipping[street][]"
										id="shipping:street1"
										value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
										title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
										class="input-text <?php echo $_streetValidationClass ?> <?php echo $streetAddressMaxLength ? 'validate-length maximum-length-' . $streetAddressMaxLength : '' ?>"
										placeholder="<?php echo $this->__('*Ex: Number, Street, Apt./Suite/Room'); ?>"
									/>
								</div>
							</div>
						</li>
						<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
						<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
							<li class="wide">
								<div class="input-box">
									<input
										type="text"
										name="shipping[street][]"
										id="billing:street<?php echo $_i ?>"
										value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
										title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>"
										class="input-text <?php echo $streetAddressMaxLength ? 'validate-length maximum-length-' . $streetAddressMaxLength : '' ?>"
										placeholder="<?php echo $this->__('*Ex: Number, Street, Apt./Suite/Room'); ?>"
									/>
								</div>
							</li>
						<?php endfor; ?>

                        <?php if(Mage::helper('core')->isModuleEnabled('Blugento_CheckoutAutocomplete')): ?>
                            <?php if (Mage::getStoreConfig('blugento_cautocomplete/general/enabled') && !Mage::getStoreConfig('blugento_cautocomplete/general/position')): ?>
                                <li class="wide autocomplete-field">
                                    <div class="field">
                                        <label for="shipping:autocomplete" class="required"><em>*</em><?php echo $this->__('City / County / Zip/Postal Code') ?></label>
                                        <div class="input-box results-autocomplete">
                                            <input type="text" name="shipping[autocomplete]" id="shipping:autocomplete" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Autocomplete')) ?>" class="shipping-autocomplete input-text required-entry" />
                                            <div id="autocomplete-list">
                                                <ul></ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            <?php endif; ?>
						<?php endif; ?>

						<?php if ($billHelper->displayRegionBeforeCity()): ?>
							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>

								<div class="field region_id">
									<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
									<div class="input-box">
										<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display: none;">
											<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
										</select>
										<script type="text/javascript">
											//<![CDATA[
											$('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
											//]]>
										</script>
										<input
											type="text"
											id="shipping:region"
											name="shipping[region]"
											value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
											class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
											style="display: none;"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field city">
										<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
										<div class="input-box">
											<input
												type="text"
												name="shipping[city]"
												id="shipping:city"
												value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
												onchange="shipping.setSameAsBilling(false);"
											/>
										</div>
									</div>
								<?php endif; ?>
							</li>

							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field city">
										<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
										<div class="input-box">
											<input
												type="text"
												name="shipping[city]"
												id="shipping:city"
												value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
												onchange="shipping.setSameAsBilling(false);"
											/>
										</div>
									</div>
								<?php endif; ?>

								<div class="field zip-code">
									<label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
									<div class="input-box">
										<input
											type="text"
											name="shipping[postcode]"
											id="shipping:postcode"
											value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>"
											class="input-text validate-postcode <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
											onchange="shipping.setSameAsBilling(false);"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>
							</li>
						<?php else: ?>
							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>

								<div class="field city">
									<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
									<div class="input-box">
										<input
											type="text"
											name="shipping[city]"
											id="shipping:city"
											value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
											class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
											onchange="shipping.setSameAsBilling(false);"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field region_id">
										<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
										<div class="input-box">
											<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display: none;">
												<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
											</select>
											<script type="text/javascript">
												//<![CDATA[
												$('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
												//]]>
											</script>
											<input
												type="text"
												id="shipping:region"
												name="shipping[region]"
												value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
												style="display: none;"
											/>
										</div>
									</div>
								<?php endif; ?>
							</li>

							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field region_id">
										<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
										<div class="input-box">
											<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display: none;">
												<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
											</select>
											<script type="text/javascript">
												//<![CDATA[
												$('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
												//]]>
											</script>
											<input
												type="text"
												id="shipping:region"
												name="shipping[region]"
												value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
												style="display: none;"
											/>
										</div>
									</div>
								<?php endif; ?>

								<div class="field zip-code">
									<label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
									<div class="input-box">
										<input
											type="text"
											name="shipping[postcode]"
											id="shipping:postcode"
											value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>"
											class="input-text validate-postcode <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
											onchange="shipping.setSameAsBilling(false);"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>
							</li>
						<?php endif; ?>

						<?php if(Mage::helper('core')->isModuleEnabled('Blugento_CheckoutAutocomplete')): ?>
                            <?php if (Mage::getStoreConfig('blugento_cautocomplete/general/enabled') && Mage::getStoreConfig('blugento_cautocomplete/general/position')): ?>
                                <li class="wide autocomplete-field">
                                    <div class="field">
                                        <label for="shipping:autocomplete" class="required"><em>*</em><?php echo $this->__('City / County / Zip/Postal Code') ?></label>
                                        <div class="input-box results-autocomplete">
                                            <input type="text" name="shipping[autocomplete]" id="shipping:autocomplete" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Autocomplete')) ?>" class="shipping-autocomplete input-text required-entry" />
                                            <div id="autocomplete-list">
                                                <ul></ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            <?php endif; ?>
						<?php endif; ?>

						<li class="fields">
							<div class="field">
								<label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
								<div class="input-box">
									<input
										type="text"
										name="shipping[telephone]"
										id="shipping:telephone"
										value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
										title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>"
										class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?> validate-length <?php echo $phoneMinLength != '' ? 'minimum-length-' . $phoneMinLength : '' ?> maximum-length-<?php echo $phoneMaxLength ?: 14 ?> validate-telephone-number"
										onchange="shipping.setSameAsBilling(false);"
									/>
								</div>
							</div>
							<?php if ($billHelper->getAttributeClass('fax')): ?>
							<div class="field">
								<label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
								<div class="input-box">
									<input
										type="text"
										name="shipping[fax]"
										id="shipping:fax"
										value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
										title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>"
										class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
										onchange="shipping.setSameAsBilling(false);"
									/>
								</div>
							</div>
							<?php endif; ?>
						</li>
						<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
							<li class="control">
								<input
									type="checkbox"
									name="shipping[save_in_address_book]"
									value="1"
									title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save in address book')) ?>"
									id="shipping:save_in_address_book"
									onchange="shipping.setSameAsBilling(false);"
									<?php if ($this->getAddress()->getSaveInAddressBook()): ?>
										checked="checked"
									<?php endif; ?>
									class="checkbox"
								/>
								<label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
							</li>
						<?php else: ?>
							<li class="no-display">
								<input type="hidden" name="shipping[save_in_address_book]" value="1" />
							</li>
						<?php endif; ?>
					</ul>
					<?php echo $this->getBlockHtml('formkey') ?>
				</fieldset>
			</li>
			<?php if ($_checkoutUseBillingShippingAddressAboveForm == 2): ?>
				<li class="control">
					<input
						type="checkbox"
						name="shipping[same_as_billing]"
						id="shipping:same_as_billing"
						value="1"
						<?php if ($this->getAddress()->getSameAsBilling()): ?>
							checked="checked"
						<?php endif; ?>
						title="<?php echo $this->__('Use Billing Address') ?>"
						onclick="shipping.setSameAsBilling(this.checked)"
						class="checkbox"
					/>
					<label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
				</li>
			<?php endif; ?>
		</ul>
		<div class="buttons-set" id="shipping-buttons-container">
			<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
			<button type="button" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue')) ?>" onclick="shipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
			<span id="shipping-please-wait" class="please-wait" style="display: none;">
	            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
	        </span>
		</div>
	</form>
	<script type="text/javascript">
			//<![CDATA[
			
			var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>', '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
			var shippingForm = new VarienForm('co-shipping-form');
			
			shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
			
			$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
			
			var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
			
			//]]>
	</script>
	
	<?php if (Mage::helper('core')->isModuleEnabled('Eadesigndev_Romcity')): ?>
		<script type="text/javascript">
					//<![CDATA[
					var normalImputShip = '<input type="text" class=" input-text required-entry absolute-advice ship2" title="City" value="" id="shipping:city" name="shipping[city]" autocomplete="off">';
		  
		  <?php if($this->getAddress()->getRegionId()): ?>
					Event.observe($('shipping-address-select'), 'change', function (event) {
						var action = CITIES_ACTION;
						var selectCountry = $('shipping:country_id').value;
						var stateId = $('shipping:region_id').value;
						var selectedCity = '<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>';
						getAjaxReqestShip(action, selectCountry, stateId, normalImput,selectedCity)
					});
		  <?php endif?>
					
					Event.observe($('shipping:region_id'), 'change', function (event) {
						var selectedCity = false;
						var action = CITIES_ACTION;
						var selectCountry = $('shipping:country_id').value;
						var stateId = $('shipping:region_id').value;
						getAjaxReqestShip(action, selectCountry, stateId, normalImputShip,selectedCity)
						
					});
					Event.observe($('shipping:country_id'), 'change', function (event) {
						var shippingCity = $('shipping:city');
						if(shippingCity!=null)
						{
							$('shipping:city').replace(normalImputShip);
						}
					});
					//]]>
		</script>
	<?php endif; ?>
<?php elseif ($_checkoutNewLayOut == 1) : ?>
	<form id="co-shipping-form" action="">
	    <ul class="form-list form-list--horizontal">
	        <?php if ($this->customerHasAddresses()): ?>
	           <li class="wide">
	               <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
	               <div class="input-box">
	                   <?php if ($_checkoutShippingAddressLayout == 2): ?>
	                       <ul id="listAddressShipping" class="list--address">
	                           <?php $i = 0; ?>
	                           <?php foreach ($customer->getAddresses() as $address): ?>
	                               <?php $data = $address->toArray(); ?>
	                               <?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']); ?>
	                               <li onclick="Blugento.Checkout.setShippingAddress(this, <?php echo $data['entity_id'] ?>);" id="blugento-shipping-address-<?php echo $data['entity_id'] ?>">
	                                   <?php echo $data['firstname'] . ' ' . $data['lastname'] ?><br />
	                                   <?php echo $data['street'] ?><br />
	                                   <?php echo $data['city'] . ',' . $data['region'] . ',' . $data['postcode'] ?><br />
	                                   <?php echo $country_name ?><br />
	                                   <?php echo $data['telephone'] ?>
	                               </li>
	                               <?php $i++; ?>
	                           <?php endforeach; ?>
	                       </ul>
	                       <div class="input-box" style="display: none;">
	                           <?php echo $this->getAddressesHtmlSelect('shipping') ?>
	                       </div>
	                   <?php else: ?>
	                       <div class="input-box">
	                           <?php echo $this->getAddressesHtmlSelect('shipping') ?>
	                       </div>
	                   <?php endif; ?>
	               </div>
	           </li>
	        <?php endif; ?>
	        <?php if ($_checkoutUseBillingShippingAddressAboveForm == 1): ?>
	            <li class="control">
	                <input
	                    type="checkbox"
	                    name="shipping[same_as_billing]"
	                    id="shipping:same_as_billing"
	                    value="1"
	                    <?php if ($this->getAddress()->getSameAsBilling()): ?>
	                        checked="checked"
	                    <?php endif; ?>
	                    title="<?php echo $this->__('Use Billing Address') ?>"
	                    onclick="shipping.setSameAsBilling(this.checked)"
	                    class="checkbox"
	                />
	                <label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
	            </li>
	        <?php endif; ?>
	        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display: none;"<?php endif ?>>
	            <fieldset>
	                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
	                <ul>
	                    <li class="fields">
	                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
	                    </li>
	                    <li class="fields">
	                        <div class="field">
	                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
	                            <div class="input-box">
	                                <input
	                                    type="text"
	                                    name="shipping[company]"
	                                    id="shipping:company"
	                                    value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
	                                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>"
	                                    class="input-text"
	                                />
	                            </div>
	                        </div>
	                    </li>
		
		                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
		                <li class="wide">
			                <div class="field">
				                <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
				                <div class="input-box">
					                <input
						                type="text"
						                name="shipping[street][]"
						                id="shipping:street1"
						                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
						                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
						                class="input-text <?php echo $_streetValidationClass ?> <?php echo $streetAddressMaxLength ? 'validate-length maximum-length-' . $streetAddressMaxLength : '' ?>"
						                placeholder="<?php echo $this->__('*Ex: Number, Street, Apt./Suite/Room'); ?>"
					                />
				                </div>
			                </div>
		                </li>
		                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
		                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
			                <li class="wide">
				                <div class="input-box">
					                <input
						                type="text"
						                name="shipping[street][]"
						                id="billing:street<?php echo $_i ?>"
						                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
						                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>"
						                class="input-text <?php echo $streetAddressMaxLength ? 'validate-length maximum-length-' . $streetAddressMaxLength : '' ?>"
						                placeholder="<?php echo $this->__('*Ex: Number, Street, Apt./Suite/Room'); ?>"
					                />
				                </div>
			                </li>
						<?php endfor; ?>

                        <?php if(Mage::helper('core')->isModuleEnabled('Blugento_CheckoutAutocomplete')): ?>
                            <?php if (Mage::getStoreConfig('blugento_cautocomplete/general/enabled') && !Mage::getStoreConfig('blugento_cautocomplete/general/position')): ?>
                                <li class="wide autocomplete-field">
                                    <div class="field">
                                        <label for="shipping:autocomplete" class="required"><em>*</em><?php echo $this->__('City / County / Zip/Postal Code') ?></label>
                                        <div class="input-box results-autocomplete">
                                            <input type="text" name="shipping[autocomplete]" id="shipping:autocomplete" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Autocomplete')) ?>" class="shipping-autocomplete input-text required-entry" />
                                            <div id="autocomplete-list">
                                                <ul></ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            <?php endif; ?>
						<?php endif; ?>

	                    <?php if ($billHelper->displayRegionBeforeCity()): ?>
							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>

								<div class="field region_id">
									<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
									<div class="input-box">
										<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display: none;">
											<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
										</select>
										<script type="text/javascript">
											//<![CDATA[
											$('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
											//]]>
										</script>
										<input
											type="text"
											id="shipping:region"
											name="shipping[region]"
											value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
											class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
											style="display: none;"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field city">
										<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
										<div class="input-box">
											<input
												type="text"
												name="shipping[city]"
												id="shipping:city"
												value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
												onchange="shipping.setSameAsBilling(false);"
											/>
										</div>
									</div>
								<?php endif; ?>
							</li>

							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field city">
										<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
										<div class="input-box">
											<input
												type="text"
												name="shipping[city]"
												id="shipping:city"
												value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
												onchange="shipping.setSameAsBilling(false);"
											/>
										</div>
									</div>
								<?php endif; ?>

								<div class="field zip-code">
									<label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
									<div class="input-box">
										<input
											type="text"
											name="shipping[postcode]"
											id="shipping:postcode"
											value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>"
											class="input-text validate-postcode <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
											onchange="shipping.setSameAsBilling(false);"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>
							</li>
						<?php else: ?>
							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>

								<div class="field city">
									<label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
									<div class="input-box">
										<input
											type="text"
											name="shipping[city]"
											id="shipping:city"
											value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
											class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
											onchange="shipping.setSameAsBilling(false);"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field region_id">
										<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
										<div class="input-box">
											<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display: none;">
												<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
											</select>
											<script type="text/javascript">
												//<![CDATA[
												$('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
												//]]>
											</script>
											<input
												type="text"
												id="shipping:region"
												name="shipping[region]"
												value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
												style="display: none;"
											/>
										</div>
									</div>
								<?php endif; ?>
							</li>

							<li class="fields">
								<?php if ($billHelper->displayCountryBeforeRegion()): ?>
									<div class="field region_id">
										<label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
										<div class="input-box">
											<select id="shipping:region_id" name="shipping[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display: none;">
												<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
											</select>
											<script type="text/javascript">
												//<![CDATA[
												$('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
												//]]>
											</script>
											<input
												type="text"
												id="shipping:region"
												name="shipping[region]"
												value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
												title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
												class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
												style="display: none;"
											/>
										</div>
									</div>
								<?php endif; ?>

								<div class="field zip-code">
									<label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
									<div class="input-box">
										<input
											type="text"
											name="shipping[postcode]"
											id="shipping:postcode"
											value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
											title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>"
											class="input-text validate-postcode <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"
											onchange="shipping.setSameAsBilling(false);"
										/>
									</div>
								</div>

								<?php if (!$billHelper->displayCountryBeforeRegion()): ?>
									<div class="field country-field">
										<label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
										<div class="input-box">
											<?php echo $this->getCountryHtmlSelect('shipping') ?>
										</div>
									</div>
								<?php endif; ?>
							</li>
						<?php endif; ?>

                        <?php if(Mage::helper('core')->isModuleEnabled('Blugento_CheckoutAutocomplete')): ?>
                            <?php if (Mage::getStoreConfig('blugento_cautocomplete/general/enabled') && Mage::getStoreConfig('blugento_cautocomplete/general/position')): ?>
                                <li class="wide autocomplete-field">
                                    <div class="field">
                                        <label for="shipping:autocomplete" class="required"><em>*</em><?php echo $this->__('City / County / Zip/Postal Code') ?></label>
                                        <div class="input-box results-autocomplete">
                                            <input type="text" name="shipping[autocomplete]" id="shipping:autocomplete" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Autocomplete')) ?>" class="shipping-autocomplete input-text required-entry" />
                                            <div id="autocomplete-list">
                                                <ul></ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            <?php endif; ?>
						<?php endif; ?>

	                    <li class="fields">
	                        <div class="field">
	                            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
	                            <div class="input-box">
	                                <input
	                                    type="text"
	                                    name="shipping[telephone]"
	                                    id="shipping:telephone"
	                                    value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
	                                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>"
	                                    class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?> validate-length <?php echo $phoneMinLength != '' ? 'minimum-length-' . $phoneMinLength : '' ?> maximum-length-<?php echo $phoneMaxLength ?: 14 ?> validate-telephone-number"
	                                    onchange="shipping.setSameAsBilling(false);"
	                                />
	                            </div>
	                        </div>
	                        <div class="field">
	                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
	                            <div class="input-box">
	                                <input
	                                    type="text"
	                                    name="shipping[fax]"
	                                    id="shipping:fax"
	                                    value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
	                                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Fax')) ?>"
	                                    class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
	                                    onchange="shipping.setSameAsBilling(false);"
	                                />
	                            </div>
	                        </div>
	                    </li>
	                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
	                        <li class="control">
	                            <input
	                                type="checkbox"
	                                name="shipping[save_in_address_book]"
	                                value="1"
	                                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save in address book')) ?>"
	                                id="shipping:save_in_address_book"
	                                onchange="shipping.setSameAsBilling(false);"
	                                <?php if ($this->getAddress()->getSaveInAddressBook()): ?>
	                                    checked="checked"
	                                <?php endif; ?>
	                                class="checkbox"
	                            />
	                            <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
	                        </li>
	                    <?php else: ?>
	                        <li class="no-display">
	                            <input type="hidden" name="shipping[save_in_address_book]" value="1" />
	                        </li>
	                    <?php endif; ?>
	                </ul>
	                <?php echo $this->getBlockHtml('formkey') ?>
	            </fieldset>
	        </li>
	        <?php if ($_checkoutUseBillingShippingAddressAboveForm == 2): ?>
	        <li class="control">
	            <input
	                type="checkbox"
	                name="shipping[same_as_billing]"
	                id="shipping:same_as_billing"
	                value="1"
	                <?php if ($this->getAddress()->getSameAsBilling()): ?>
	                    checked="checked"
	                <?php endif; ?>
	                title="<?php echo $this->__('Use Billing Address') ?>"
	                onclick="shipping.setSameAsBilling(this.checked)"
	                class="checkbox"
	            />
	            <label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
	        </li>
	        <?php endif; ?>
	    </ul>
	    <div class="buttons-set" id="shipping-buttons-container">
	        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	        <button type="button" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue')) ?>" onclick="shipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
	        <span id="shipping-please-wait" class="please-wait" style="display: none;">
	            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
	        </span>
	    </div>
	</form>
	<script type="text/javascript">
	//<![CDATA[
	
	    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>', '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
	    var shippingForm = new VarienForm('co-shipping-form');
	
	    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
	
	    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
	
	    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
	
	//]]>
	</script>
	
	<?php if (Mage::helper('core')->isModuleEnabled('Eadesigndev_Romcity')): ?>
	    <script type="text/javascript">
	        //<![CDATA[
	        var normalImputShip = '<input type="text" class=" input-text required-entry absolute-advice ship2" title="City" value="" id="shipping:city" name="shipping[city]" autocomplete="off">';
	
	        <?php if($this->getAddress()->getRegionId()): ?>
	        Event.observe($('shipping-address-select'), 'change', function (event) {
	            var action = CITIES_ACTION;
	            var selectCountry = $('shipping:country_id').value;
	            var stateId = $('shipping:region_id').value;
	            var selectedCity = '<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>';
	            getAjaxReqestShip(action, selectCountry, stateId, normalImput,selectedCity)
	        });
	        <?php endif?>
	
	        Event.observe($('shipping:region_id'), 'change', function (event) {
	            var selectedCity = false;
	            var action = CITIES_ACTION;
	            var selectCountry = $('shipping:country_id').value;
	            var stateId = $('shipping:region_id').value;
	            getAjaxReqestShip(action, selectCountry, stateId, normalImputShip,selectedCity)
	
	        });
	        Event.observe($('shipping:country_id'), 'change', function (event) {
	            var shippingCity = $('shipping:city');
	            if(shippingCity!=null)
	            {
	                $('shipping:city').replace(normalImputShip);
	            }
	        });
	        //]]>
	    </script>
	<?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
	//<![CDATA[
	Validation.add('validate-telephone-number', 'Please enter a valid phone number. For example +40741234567', function(v) {
		return Validation.get('IsEmpty').test(v) || /^\+?(?:[0-9] ?){6,14}[0-9]$/.test(v);
	});
	//]]>
</script>

<script type="text/javascript">
	//<![CDATA[
	document.observe('dom:loaded', function() {
		Validation.add('validate-postcode', 'Please enter a valid zip code. For example 90602 or 90602-1234.', function(v) {
			if (document.getElementById('shipping:country_id').value === 'RO') {
				return Validation.get('IsEmpty').test(v) || /(^\d{6}$)/.test(v);
			} else {
				return true;
			}
		});
	});
	
	Event.observe(document.getElementById('shipping:country_id'), 'change', function (event) {
		Validation.add('validate-postcode', 'Please enter a valid zip code. For example 90602 or 90602-1234.', function(v) {
			if (event.target.value === 'RO') {
				return Validation.get('IsEmpty').test(v) || /(^\d{6}$)/.test(v);
			} else {
				return true;
			}
		});
	});
	//]]>
</script>