<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php $trackingInfo = Mage::helper('blugento_sales')->getTrackingInfoByOrder($_order); ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('invoce_link') ?>
    <?php echo $this->getChildHtml('smartbill_invoice_link') ?>
    <?php echo $this->getChildHtml('awb_link') ?>
    <p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<div class="box-info box-account">
    <dl class="order-info">
        <dd>
            <?php $_links = $this->getLinks(); ?>
            <ul id="order-info-tabs">
            <?php foreach ($_links as $_link): ?>
                <?php if($_link->getUrl()): ?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li class="current"><?php echo $_link->getLabel() ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
        </dd>
    </dl>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Address') ?></h2>
                </div>
                <div class="box-content">
                    <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Shipping Method') ?></h2>
                </div>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?php echo $_order->getShippingDescription() ?>
                    <?php else: ?>
                        <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                    <?php endif; ?>
                </div>
                <div class="box-content">
                    <?php if (count($trackingInfo)): ?>
                        <p><strong><?php echo $this->__('AWB') ?>:</strong></p>
                        <?php foreach ($trackingInfo as $tracks): ?>
                            <?php foreach ($tracks as $track): ?>
                                <div>
                                    <?php echo $track['title'] ?>:
                                    <?php if (isset($track['carrier_code']) && $track['carrier_code'] == 'bgfancourier'): ?>
                                        <a target="_blank" href="https://www.fancourier.ro/en/awb-tracking/?xawb=<?php echo $this->escapeHtml($track['number']); ?>"><strong><?php echo $this->escapeHtml($track['number']); ?></strong></a>
                                    <?php elseif (isset($track['carrier_code']) && $track['carrier_code'] == 'bgurgentcargus'): ?>
                                        <a target="_blank" href="https://app.urgentcargus.ro/Private/Tracking.aspx?CodBara=<?php echo $this->escapeHtml($track['number']); ?>"><strong><?php echo $this->escapeHtml($track['number']); ?></strong></a>
                                    <?php else: ?>
                                        <?php echo $this->escapeHtml($track['number']); ?>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <div class="col2-set order-info-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Billing Address') ?></h2>
                </div>
                <div class="box-content">
                    <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box box-payment">
                <div class="box-title">
                    <h2><?php echo $this->__('Payment Method') ?></h2>
                </div>
                <div class="box-content">
                    <?php echo $this->getPaymentInfoHtml() ?>
                </div>
            </div>
        </div>
    </div>
</div>
