<div class="block block-tags">
    <div class="block-title">
        <strong><span><?php echo $this->__('Tags') ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <?php
                $_size = 13 + 2 * max(floor(($_tag->getRatio() * 10 - 1) / 2), 0);
                if ($_size > 30) {
                    $_size = 30;
                }
                ?>
                <li data-ratio="<?php echo $_tag->getRatio() ?>"><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size: <?php echo $_size ?>px;"><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <div class="actions">
            <a href="<?php echo $this->getUrl('tag/list') ?>"><?php echo $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
