<?php
/**
 * Customer reset forgotten password form template
 *
 * @see Mage_Customer_Block_Account_Changeforgotten
 */
?>
<div class="account-resetforgottenpassword">
    <div class="page-title">
        <h1><?php echo $this->__('Reset a Password'); ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml(); ?>
    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate">
        <div class="fieldset">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
            <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
        </div>
    </form>
    <script>
    /*<![CDATA[*/
        var dataForm = new VarienForm('form-validate', true);
    /*]]>*/
    </script>
</div>
